### ISSUE TITLE
Adding Binaries in Images

### ISSUE THREAD

**Issue by tsusadivyago** [pivotal/kpack#1003]
Hi,

I have a sample java based hello world spring boot Gradle project. I want to add other tools in the containers like wget, curl, and git.
I am using paketo build packs to build images. I have a requirement to include binaries of other tools in the image.
For Ex: wget,curl,git in /usr/local/bin.

I have gone through a lot of workarounds:
Using custom buildpacks
Creating a new image with the docker file

I want to avoid any overhead or maintenance work and I want CNB to handle any deps.

Hence looking for a better approach, How can I achieve this using kpack and how to add mixins in kpack stack? Any help or suggestion would help a lot.

**Comment by tylerphelan** [comment]
@tsusadivyago 
Does the [full paketo stack](https://github.com/paketo-buildpacks/bionic-full-stack) fit your use case? It contains wget, curl, and git.

Besides the curated [stacks from paketo](https://github.com/paketo-buildpacks/stacks), your best bet is a [custom buildpack](https://buildpacks.io/docs/buildpack-author-guide/) or to [create your own stack](https://buildpacks.io/docs/operator-guide/create-a-stack/)

**Comment by tsusadivyago** [comment]
yes, paketo stack fits 99% requirement.

but we need terraform binary in the container.

what we are doing now is (2 approaches):

- Keeping the terraform binary in source code with other files this binary is also copied to the meta.inf... folder in the workspace
- we are creating an image and later using the docker file to create another image with terraform installed.

Is creating a custom pack or stack the only option I am left with?

I want to know how other devs are handling this use case, how are you getting your binaries in the container?

**Comment by robdimsdale** [comment]
Concretely, to add a binary to an existing stack I would do the following:
1. clone the stack repo in question (e.g. `jammy-full-stack`)
2. parse the `stack.toml` file with a TOML parser
3. add the required packages (and PPAs if necessary) to the package list
4. write the `stack.toml` file back
5. run `jam create-stack` with the location of the updated `stack.toml`.

If you want to install something that isn't available via a package, then I would suggest you instead modify the Dockerfiles for `build` and `run` to download it via `wget`.

**Comment by tsusadivyago** [comment]
Hey, Thanks for the reply. I will try these out.

**Comment by tylerphelan** [comment]
please re-open the issue if you have questions!
