### ISSUE TITLE
Enable configuring the creation time

### ISSUE THREAD

**Issue by imurata** [pivotal/kpack#1009]
Hi,
Gitlab container registry displays the creation time on the GUI, so I am always shown that all container creation times are 1980.
I'd like to use buildpack's `--creation-time` option to work around this problem, but it isn't implemented in kpack yet.
Do you have a plan to implement `--creation-time` option?

Related ticket:
https://github.com/buildpacks/pack/issues/931
https://github.com/buildpacks/pack/issues/1281

**Comment by tylerphelan** [comment]
Thank you for this issue! This will be related to https://github.com/pivotal/kpack/issues/998
