### ISSUE TITLE
Could we move to go modules?

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#103]
Currently, the instructions to fetch the repo, play with samples, and run the `logs` CLI are:

```
git clone https://github.com/pivotal/kpack \
   $GOPATH/src/github.com/pivotal/kpack
cd $GOPATH/src/github.com/pivotal/kpack
dep ensure
go run ./cmd/logs
```

If we move to go modules, then I think these instructions become nicer, and less dependent on old `$GOPATH`:

```
git clone https://github.com/pivotal/kpack
cd kpack
go run ./cmd/logs
```

**Comment by djoyahoy** [comment]
We attempted this migration but encountered issues with codegen and the version of kubernetes that knative pulls in. So I'm going to reopen this issue until we have a path forward.

**Comment by scothis** [comment]
Probably the easiest path forward is to use kubebuilder 2. We started to use it for riff and I'm happy so far. The only downside I've encountered is that an api server and etcd are created to run the tests. Knative had a nice setup with fake clients.

**Comment by matthewmcnew** [comment]
I do ❤️ our knative fake tests
