### ISSUE TITLE
How can I add my own CNBs?

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#104]
In CF we have `cf create-buildpack my-buildpack.zip` or we can override the discovery of buildpacks with `cf push -b my-buildpack -b my-other-buildpack`; how do I do this with kpack?

Do I need to [externally] create a custom builder that contains a specific version of my extra buildpacks? https://buildpacks.io/docs/using-pack/working-with-builders/

Or is there a `pack build --buildpack` equivalent option for an Image?

**Comment by drnic** [comment]
@sclevine is a custom builder image created when I use `pack build test-ruby-app --buildpack ~/workspace/make-a-buildpack/ruby-cnb ...`?

**Comment by mgibson1121** [comment]
@drnic As Stephen mentioned, the interface to control buildpacks that are used when builds executes will live in the `CustomBuilder` resource.  The first in a cluster of stories to enable this functionality was just delivered in #203.  Given that, I'm going to close this story, but happy to keep you posted on our progress and feedback on this interface is welcome.
