### ISSUE TITLE
Automatically create a builder for cloudfoundry/cnb:cflinuxfs3

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#105]
I'm not yet sure why I needed to create a Builder as its just a reference to the standard https://hub.docker.com/r/cloudfoundry/cnb images. Could a Builder be automatically created when installing the `release.yml`? Or two of them - one for `cloudfoundry/cnb:cflinuxfs3` and one for `cloudfoundry/cnb:bionic`?

Bonus question: what is `cloudfoundry/cnb:bionic` builder useful for, compared to `cloudfoundry/cnb:cflinuxfs3`? https://hub.docker.com/r/cloudfoundry/cnb suggests that `:cflinuxfs3` is better/necessary for more buildpacks.

**Comment by matthewmcnew** [comment]
I like the idea of creating a builder automatically to ease the setup. However, It is unclear which namespace we would create it in. Once we create a non namespace scoped ClusterBuilder in https://github.com/pivotal/kpack/issues/72, we can revisit this and create an initial builder.

The `cloudfoundry/cnb:bionic` builder is built on top of the relatively slim [ubuntu bionic](https://github.com/buildpack/stacks/tree/master/bionic) stack. 

The `cloudfoundry/cnb:cflinuxfs3` is built on top of the [cflinuxfs3](https://github.com/cloudfoundry/cflinuxfs3) stack which is much larger and includes more dependencies. This enable the cflinuxfs3 builder to support more buildpacks today (python, php) but, results in a larger built image. 

Eventually, this complexity should be simplified for end users with the upcoming [CNB mixin functionality](https://github.com/buildpack/rfcs/blob/master/text/0006-stage-specific-mixins.md).

**Comment by matthewmcnew** [comment]
We updated the install documentation to walk through builder setup of a ClusterBuilder. https://github.com/pivotal/kpack/blob/master/docs/install.md.

Unfortunately, it is problematic to add an initial builder to the release.yaml. CRDs take time to become ready and the resource will often be rejected because the api server hasn't been fully configured yet

**Comment by matthewmcnew** [comment]
@drnic Can we close this issue for now?
