### ISSUE TITLE
draft blog post for review

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#106]
@matthewmcnew if you've got time, could you review my blog post for inaccuracies, or comments you'd like to rebut? 😄 

https://starkandwayne.com/blog/p/b0abb589-69e6-4e75-a02d-dde3f8ceef4d/

**Comment by drnic** [comment]
Blog post scheduled to publish on Monday. Will close issue. Thanks @sclevine

**Comment by matthewmcnew** [comment]
Sorry, for my late reply here. 

One quick update, with: https://github.com/pivotal/kpack/pull/109 the -kubeconfig argument can be removed from the logs command. That should now be as simple as:

> logs -image sample

Excited for the blog post to go out on Monday!
