### ISSUE TITLE
Failed to authorize using AZURE_CONTAINER_REGISTRY_CONFIG in kpack 0.7.0 and above versions

### ISSUE THREAD

**Issue by smile37773** [pivotal/kpack#1065]
Failed to create builder due to UNAUTHORIZED  

![image](https://user-images.githubusercontent.com/34502364/199422888-d817a125-3801-43ab-b111-ce7398344a10.png)

The AZURE_CONTAINER_REGISTRY_CONFIG doesn't  work both for msi and service principal
The credential we used to push images is stored in /etc/kubernetes/azure.json
![Screenshot 2022-11-02 163616](https://user-images.githubusercontent.com/34502364/199440209-9f85c215-9c8d-4ccd-a09f-23012f3942c5.png)

Because of the error above I deleted the labels in kpack namespace:
![image](https://user-images.githubusercontent.com/34502364/199440783-e8869e2c-5ef6-4e15-9223-3d805c794c62.png)

I am not sure if there are related.

Similar issue: https://github.com/pivotal/kpack/issues/1005

**Comment by matthewmcnew** [comment]
Hi @smile37773 ,

The Azure credential helper uses the [azure credential provider](https://github.com/vdemeester/k8s-pkg-credentialprovider/tree/master/azure) (extracted from the kubernetes repo) and is configured to read the `/etc/kubernetes/azure.json` config to function. So, it needs to be able to utilize a hostPath volume mount to read the necessary credentials. If that is an issue in your environment the kpack-controller also pulls in the [Azure Docker credential helper](https://github.com/chrismellard/docker-credential-acr-env) and can be configured with:

```
AZURE_CLIENT_ID=<clientID>
AZURE_CLIENT_SECRET=<clientSecret>
AZURE_TENANT_ID=<tenantId>
```

- Cheers!

**Comment by smile37773** [comment]
@matthewmcnew  I try to config
```
AZURE_CLIENT_ID=<clientID>
AZURE_CLIENT_SECRET=<clientSecret>
AZURE_TENANT_ID=<tenantId>
```
But msi is unsupportted.   Besides, it's hard for us to determine if MSI is enabled when installing kpack. please read the configurations in `/etc/kubernetes/azure.json`.

**Comment by smile37773** [comment]
@matthewmcnew  How can I do to allow the kpack controller to not need to run in the restricted [pod security standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/).  I already deleted the labels in kpack namespce but I still met the  authorize error when creating builders.
![image](https://user-images.githubusercontent.com/34502364/199870387-43e0770d-335a-40ef-bba8-483c0ab29f85.png)

**Comment by smile37773** [comment]
> @matthewmcnew How can I do to allow the kpack controller to not need to run in the restricted [pod security standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/). I already deleted the labels in kpack namespce but I still met the authorize error when creating builders. ![image](https://user-images.githubusercontent.com/34502364/199870387-43e0770d-335a-40ef-bba8-483c0ab29f85.png)

@matthewmcnew  It works when I changed the restricted policy to privileged policy.  Is there a potential security concern?

**Comment by matthewmcnew** [comment]
That depends on if you are comfortable running the kpack pods within the privileged policy.
