### ISSUE TITLE
Build pods are evicted midway during the build

### ISSUE THREAD

**Issue by ghousemohamed** [pivotal/kpack#1106]
When I do `kubectl get image_name` I can see that the status of the image indicates that it is `False`. But I when I try to inspect the pod on which the build was running on by running `kubectl get pod image-build-pod-name`, I'm getting: `Error from server (not found)`. Ideally even if there was a failure during the build due some misconfiguration it should not be removing the pod since the logs from the pod will have the information regarding why it failed.

This happens very randomly. I'm running multiple builds and all of them succeed mostly, but at times when there is failure, the pod seems to be evicted.

Another side effect I noticed is that when I try to access the logs of the build using the kpack-cli by running `kp build logs image_name`, the command hangs and does not return anything for quite a while. I believe this is because the kpack-cli was not able to find the associated pod from which it was to retrieve the logs from.

Is there something I'm missing which is causing the pods to be evicted or removed completely midway while the build is happening? I've also added pod disruption budgets to the pods which are provisioned by the kpack, to see if that would do anything, but to no avail.

**Comment by tomkennedy513** [comment]
Closing this for now, please reopen if you still have this problem
