### ISSUE TITLE
How to pass args to build pod containers

### ISSUE THREAD

**Issue by zhoufenqin** [pivotal/kpack#1143]
Sometimes I need to pass some args to build pod containers, like enable debug log for `analyze` step
In lifecycle, it accepts `-log-level=debug` arg, but in kpack, all the args are determined by cnbimage, I don't see that it can accept additional args in the [build_pod.go](https://github.com/pivotal/kpack/blob/main/pkg/apis/build/v1alpha2/build_pod.go#L268).

Is there any way to support the feature or any plan to provide the feature?

**Comment by tomkennedy513** [comment]
This is currently not possible, but this is a long standing request in kpack and is being tracked by #391. closing this as a duplicate
