### ISSUE TITLE
request: store git metadata in image metadata

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#116]
When I inspect a resulting Docker image, I'd like to be able to determine what git repo, branch, and sha were used (in addition to the buildpack information, which is already included in the docker image metadata).

Could we store the git repo/branch/sha details from the source app into the resulting docker image, as we do now with buildpacks?

**Comment by matthewmcnew** [comment]
There already is an existing RFC to add source metadata to images built from cloud native buildpacks.  https://github.com/buildpack/rfcs/pull/9

Once this RFC is accepted and implemented kpack built images will include the source metadata.
