### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by dmcintyre-pivotal** [pivotal/kpack#119]
The installation instructions say to simply

`kubectl -f release.yml`

But there is no release.yml file in the repo.

Also, pack is a dependency, but the latest version of pack does not with with Docker CE (on a Mac at least) since pack uses docker API version 1.38 and the maximum accepted by DOcker CE is 1.35

**Comment by dmcintyre-pivotal** [comment]
Never mind, turns out that I needed a reboot after installing a newer version of Docker.

**Comment by sclevine** [comment]
In case it’s helpful: kpack does not depend on pack (it uses the lifecycle directly, and doesn’t use a Docker daemon to build images). Also, release.yaml is attached to the GitHub release.

**Comment by joaopapereira** [comment]
Just a little bit more clarity.
When using the scripts in `hack` folder we do require pack to create the images.
So `kpack` when running does not need pack but if you are using the scripts to build `kpack` it will needs `pack`
