### ISSUE TITLE
release.yaml for latest/nightly version?

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#120]
I'm deploying kpack from the `release.yaml` attached to v0.0.3 https://github.com/pivotal/kpack/releases

Is there a `latest-release.yaml` that's produced during CI or similar that explicitly references latest kpack images that I could also try?

(I ran `./hack/release.sh drnic tmp/latest-release.yaml` in the meantime)

**Comment by joaopapereira** [comment]
Hello, at this point we do not publish any Release Candidate version from our Pipelines, but eventually we can start doing so.

Nevertheless you can still use the `release.sh` as you mentioned to create a new release
