### ISSUE TITLE
At `RESTORE`, if a valid registry tag for a cache has been specified, it fails to use the cached layers

### ISSUE THREAD

**Issue by ghousemohamed** [pivotal/kpack#1228]
<img width="470" alt="Screenshot 2023-05-26 at 6 21 25 PM" src="https://github.com/pivotal/kpack/assets/56545288/7c1131e9-1aab-4a4c-8b30-8f272a80158f">

This the warning I'm seeing. Using the `pack` binary, I know what is the flag I need to use for this. How do I get around this in kpack's context? Is there a way in which I can add `-cache-image` option to the `restore` init container using a flag?

**Comment by chenbh** [comment]
This can be done using the [`.spec.cache`](https://github.com/pivotal/kpack/blob/main/docs/image.md) fields. You can choose between caching via k8s PVs or the registry
