### ISSUE TITLE
Rebase app when new run image is available

### ISSUE THREAD

**Issue by mgibson1121** [pivotal/kpack#135]
As an app owner
I want build service to rebase my app to resolve a new run image dependency
So that the app can utilize the new run image without a rebuild

**Given** a series of images were built by kpack utilizing a particular run image name <> version combination
**When** a different run image name <> version combination becomes available in my registry 
**Then** the most recent image in the stream is rebased utilizing the new run image to resolve this change

**Comment by ashwin-venkatesh** [comment]
Closed with #140
