### ISSUE TITLE
Make the kpack Pivotal Tracker project public, or delete the integration

### ISSUE THREAD

**Issue by scothis** [pivotal/kpack#142]
`kpack` is an open source project. It's hostile to the community to see notifications on issues saying that it is being tracked and managed in a place that is not also open to the public.

Minimally, the Pivotal Tracker project should be make public. Even better, use tools that treat GitHub issues as the source of truth to avoid forking information and discussions.

**Comment by sclevine** [comment]
The private tracker referenced in those notices is only used to prioritize kpack against other, non-kpack work. There is no additional context in that tracker.

We should figure out a way to disable the above bot comment though, as it’s very misleading.

**Comment by matthewmcnew** [comment]
@scothis We disabled the cf-gitbot integration. 

Closing for now.
