### ISSUE TITLE
suggestion: logs to show "Done" at the end

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#147]
Watching TGIK briefly I saw the "Oh I didn't know my build was completed" comment that I'd made to myself each time I run `logs`.

Afaik, `logs` just shows the STDOUT/STDERR from each init container of the build pod. Therefore, if we added a final init container that said "Done", then we'd get a free "Logs for this build are done now" message for the `logs` CLI?

**Comment by matthewmcnew** [comment]
Resolved in https://github.com/pivotal/kpack/pull/154
