### ISSUE TITLE
Document/support using image registries over http rather than https.

### ISSUE THREAD

**Issue by GrahamDumpleton** [pivotal/kpack#196]
Documentation doesn't indicate how you can use an image registry over `http`. The prepare step appears to always use `https`.

If this isn't currently supported, should consider supporting `http` as well as `https`, as an image registry deployed into the same Kubernetes cluster may for convenience only use `http`.

**Comment by matthewmcnew** [comment]
kpack does not currently explicitly provide support for accessing an insecure registry over `http`. However, kpack utilizes http://github.com/google/go-containerregistry which will fall back to `http` in a few different [cases](https://github.com/google/go-containerregistry/blob/e1c5762cb945605669ed5fcb3124e3f839e5cc79/pkg/name/registry.go#L84). 

[Conveniently](https://github.com/google/go-containerregistry/blob/e1c5762cb945605669ed5fcb3124e3f839e5cc79/pkg/name/registry.go#L31), accessing registries with the kubernetes dns record `*.cluster.local` are available via `http` such as `my-registry.cluster.local`.

**Comment by GrahamDumpleton** [comment]
Okay, so have confirmed that using `.cluster.local` will allow use of HTTP.

Next related question, is there a way to tell it to use a specific certificate for a certificate authority when connecting using HTTPS?

The image registry in the cluster is using a certificate for HTTPS generated by the cluster. Does the Secret have an annotation that can be set to provide that CA file when talking to the image registry?

**Comment by matthewmcnew** [comment]
Discussion on custom CA certs on https://github.com/pivotal/kpack/issues/207. Closing this issue.

**Comment by cmoulliard** [comment]
> Okay, so have confirmed that using `.cluster.local` will allow use of HTTP.

That fails for me 
```
Status:
  Conditions:
    Last Transition Time:  2021-03-09T11:03:41Z
    Message:               Get "http://kube-registry.infra.svc.cluster.local:5000/v2/": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
    Status:                False
    Type:                  Ready
  Observed Generation:     1
  Stack:
Events:  <none>
```
