### ISSUE TITLE
Writing to the cache volume fails with permission denied when using Kind

### ISSUE THREAD

**Issue by djoyahoy** [pivotal/kpack#201]
Builds fail with the following error message:
```
[restore] ERROR: failed to create volume cache: initializing staging directory '/cache/staging': mkdir /cache/staging: permission denied
```

The root cause is documented here: https://github.com/kubernetes-sigs/kind/issues/830

A possible work around is to create a StorageClass that uses a local volume, create a PersistentVolume that uses the local StorageClass, and point the claim at that volume.

**Comment by BenTheElder** [comment]
sorry about that.

another subpar option is to use containers with UID=0, or at least long enough to change the permissions on the volume.

i'd probably recommend trying one of the options mentioned in discussion on https://github.com/kubernetes-sigs/kind/issues/118

**Comment by matthewmcnew** [comment]
Closing this with https://github.com/kubernetes-sigs/kind/issues/118 closing. Works great!

**Comment by BenTheElder** [comment]
Excellent! Sorry about the noise 😅
