### ISSUE TITLE
Azure DevOps not able fetch code from Git repo

### ISSUE THREAD

**Issue by amitmele** [pivotal/kpack#213]
Using Azure DevOps private registry, 

Authorisation is successful but 
While building Image getting bellow error

PS C:\Test\kpack\kpack-ms> .\logs.exe -image sample-image
prepare:main.go:78: unable to fetch git repository: unexpected client error: unexpected requesting "https://private-test.visualstudio.com/PROJECT/_git/test-sb-kp-ms/git-upload-pack" status code: 400

**Comment by amitmele** [comment]
Ref May Help: https://github.com/argoproj/argo-cd/issues/1067, issue mostly with go-git library

**Comment by matthewmcnew** [comment]
It looks like this is a direct result of the issue in the go-git library. https://github.com/src-d/go-git/issues/1058

**Comment by lsilvapvt** [comment]
Any plans to address this issue with the product? It prevents the adoption of the product by any customer that uses Azure DevOps repositories in the field.

**Comment by tylerphelan** [comment]
new issue: https://github.com/go-git/go-git/issues/64

**Comment by rajivmca2004** [comment]
Any update on this, when it will be fixed? Our partner/customer is getting impacted with this.

**Comment by phillebaba** [comment]
@rajivmca2004 I have created a PR https://github.com/go-git/go-git/pull/200 with a fix that would make it work for Azure DevOps.

**Comment by djoyahoy** [comment]
@phillebaba Thank you for letting us know and for your hard work on that PR!

**Comment by dirien** [comment]
hi, 

i just wanted to mention that @phillebaba enabled in the GitOps Toolkit the git2go library as an alternative. This approach could be useful here too?

**Comment by phillebaba** [comment]
Yep so our solution after a failed attempt at adding multi_ack support to go-git was to switch over to git2go. It is probably the only other proper git client for golang. After spending some time with reading git wire protocol specs I can say that fully implementing multi_ack and multi_ack_detailed is not an easy job in go-git and would require someone who could work on it full time for some weeks. This makes implementing it in go-git improbable.

Saying that, git2go does have its limitations as well that I found along the way. Hopefully this would help you guys when choosing if it is right for you to switch.
* git2go is a golang binding for libgit2 which is built in C. This means that if you want to run anything using git2go locally you will need to install the libgit2 library. This is pretty easy on macOS and most linux distros, not to sure about Windows. If you run everything in a container this really is not an issue.
* Shallow cloning is currently not supported, which was a big deal for us. There is a PR that has been open for a couple of years, but has sadly not been merged yet. It is still active to this day.
* SSH key validation is a bit tricky if you want to do it in memory as it does not expose data to use the standard go method. I have looked into solving this but it may take a while. Until then you could just use the solution flux uses which is not as nice as the standard go method.

**Comment by matthewmcnew** [comment]
Thanks for the summary @phillebaba. We will look at git2go. The shallow cloning/ssh key validation might be a bit of a hurdle for us. We will need to investigate.
