### ISSUE TITLE
Add user friendly logs or some other way to signal the current observed repo state for each repo

### ISSUE THREAD

**Issue by djoyahoy** [pivotal/kpack#232]
Add a way to show what is happening with source resolving so that we can answer questions like: 
* What is the current commit that will be built?
* When was the last time I polled git for updates?

**Comment by matthewmcnew** [comment]
Does the source resolver status provide this?

**Comment by djoyahoy** [comment]
For the most part yes. I think it would be nice to show the result of the most recent poll?

For context, this came about from users being confused as to whether or not polling was actually happening and was a suggestion to help adoption. Open to many different kinds of iterations on this idea.

**Comment by matthewmcnew** [comment]
Closing as this request has gone stale. Please reopen if it is still requested.
