### ISSUE TITLE
First step in installation documentation does not have enough information to get started

### ISSUE THREAD

**Issue by blgm** [pivotal/kpack#235]
Hi,

The [docs](https://github.com/pivotal/kpack/blob/master/docs/install.md) say you should:
```
kubectl apply  --filename release.yaml
```

The [latest releases](https://github.com/pivotal/kpack/releases) say you should:
```
kubectl apply -f release-0.0.5.yaml
```

But I can't find either of those files in this repo. How do I get started?

**Comment by matthewmcnew** [comment]
Hi @blgm,

Thanks for the catch. We need to clarify those docs. The `release-0.0.5.yaml` is available as a downloadable asset on the [release](https://github.com/pivotal/kpack/releases/tag/v0.0.5). 

You can install `0.0.5` today with the url directly like this:

`kubectl apply -f https://github.com/pivotal/kpack/releases/download/v0.0.5/release-0.0.5.yaml`
