### ISSUE TITLE
Provide SDK to manage kpack

### ISSUE THREAD

**Issue by allxiao** [pivotal/kpack#239]
Related to #233 .

Currently, it's difficult to integrate kpack in other language platform except for Go. We may need some language specific SDK / tools to ease the integration process. This may include:

* installation of kpack
* kpack custom resource management
* notification for the build status update
* log streaming
* error handling (categorize the error, and possible reactions)
* retry

Without this, we need to dig into the source for every model and logic change when we need to use / upgrade to a new version.

**Comment by matthewmcnew** [comment]
Closing as this request has gone stale with the introduction of an open-api spec. Please reopen if it is still requested.
