### ISSUE TITLE
Imperative style kpack resource management

### ISSUE THREAD

**Issue by ArieShout** [pivotal/kpack#240]
Kpack is built on top of the Kubernetes resource model, which is eventual consistent. This makes the resource monitoring difficult:

* The behavior of build creation is non-deterministic: if I update the image spec, a new build may, or may not be created.
* No blocking call: for different resources monitoring, we need to setup different polling mechanism, or setup a event router in the cluster. That requires knowledge of the kpack resource status / condition details, which needs to dig into the source code.

It may be helpful to have some abstraction on top of the raw kpack, maybe in SDK, to allow different programming paradigm. This definitely can be achieved in the integration side, but it may be useful to have some centralized abstraction so that all the integration parties do not need to repeat the work.

**Comment by matthewmcnew** [comment]
We can track SDKs here: https://github.com/pivotal/kpack/issues/239. I am going to close this for now.
