### ISSUE TITLE
Enable correlation of changes to the kpack resources

### ISSUE THREAD

**Issue by ArieShout** [pivotal/kpack#241]
On the integration side, we need to correlate all the changes to the external systems. And when we receive some updates from external system, we need to be able to identify the source in the internal system quickly. This requires us to be able to pass some data to the resource created, as well as the sub-resource created.

`Generation` is not a good candidate, because:
* it doesn't have any semantics, so we need to build extra index in our system to lookup for certain generation and map back to internal resource
* the Kubernetes eventual consistent model will make the generation difficult to reason about

It may be good to be able to pass certain labels / annotations (e.g., with `custom.kpack.io/` prefix) to the derived resources.

**Comment by matthewmcnew** [comment]
Annotation propagation provided in https://github.com/pivotal/kpack/pull/274.
