### ISSUE TITLE
Lack the control on the resulting Build from Image

### ISSUE THREAD

**Issue by allxiao** [pivotal/kpack#242]
Currently the generation of Build from Image happens automatically, this

* stop further build from starting if a previous build is stuck
* recreates a new build if we clear the existing finished build
* no way to terminate long-running build

A workaround is to use raw Build instead of Image, but that add extra effort to the integration side and lost some of the key features provided by Image.

Apart from the automatic build behavior, we may check if we can offer more control over the build, manually.

**Comment by matthewmcnew** [comment]
I created #245 to track the ability to terminate/cancel a build.
