### ISSUE TITLE
Missing documentation how to execute a single Cloud Native Buildpack image build.

### ISSUE THREAD

**Issue by kinkerl** [pivotal/kpack#246]
Hi all,

The readme states that "kpack also provides a build type to execute a single Cloud Native Buildpack image build."

I can not find any information about this in the documentation. Is it missing?

**Comment by ashwin-venkatesh** [comment]
hey @kinkerl ,
You're right. We have not currently documented how to setup a stand-alone build. We will put something together in the near future and update our READMEs. Thanks for bringing this up 👍

**Comment by kinkerl** [comment]
Hey, thank you for getting back to me!
I would love to test / help if I can. Just ping me :smile:

**Comment by ashwin-venkatesh** [comment]
@kinkerl https://github.com/pivotal/kpack/pull/277 should add some documentation around creating a stand alone build. Feel free to give the example a whirl and leave us feedback.
