### ISSUE TITLE
Additional ideas for validation when applying `CustomBuilder` resource

### ISSUE THREAD

**Issue by mgibson1121** [pivotal/kpack#252]
These ideas stemmed from accepting  our initial pass at improving validation in #11 

`CustomBuilder` resource:

* Seems a little weird that `baseBuilderImage` can be left blank
* Same thing for 
```
  store:
    image:
```

**Comment by matthewmcnew** [comment]
@mgibson1121 There are a couple of disparate validation ideas in this. Do you mind breaking them into separate issues?

**Comment by mgibson1121** [comment]
Split the validation ideas around not being able to reference names for resources that do not exist yet into a different story: #255

**Comment by matthewmcnew** [comment]
`CustomBuilder.spec.baseBuilderImage` and `CustomBuilder.spec.store.image` are no longer properties on the `CustomBuilder`. They are replaced with references to `stack` and  `store` respectively. 

The CustomBuilder validates the presence of `stack` and `store`. The Stack resource validates that all its fields are present and valid and the Store resource validates that it has images and they are valid. 

I think that satisfies this issue. We can reopen if we missed something?
