### ISSUE TITLE
Make `image.spec.tag` mutable

### ISSUE THREAD

**Issue by metacpp** [pivotal/kpack#289]
Hello,

In our system, we need to have the capability to re-tag the image with different tag name, while the new version (`0.0.6`) of kpack does not allow to do it. We noticed that it actually worked in the earlier version of kpack, can we add it back ? Appreciate the helps here.

**Comment by ashwin-venkatesh** [comment]
Hey @metacpp,

Could you elaborate on the use-case of retagging the same image config multiple times? Philosophically, we see the image tag as something that uniquely identifies the image and the object that gets updated across successive builds. It would help if we understood the whys behind updating the tag on an image

**Comment by matthewmcnew** [comment]
From conversations with @metacpp: 

Previously, It was useful in kpack to update the `Image.spec.tag` to produce images tagged with the status of the source. For example, this could be a version number, upload id or other metadata about the current image. If that `Image.spec.tag` is immutable it is not possible for produced images to be automatically tagged with a meaningful tag.

It probably still makes sense for the Image to have an immutable tag to maintain the "philosophy" that it is ongoing stream of updates to an image. However, optional additional tags could be configured on the image resource. That would enable the original tagging usecase without fundamentally changing the semantics of the image resource. (Essentially a custom imageTaggingStrategy).

If this was implemented, we would need to figure out how handle updates to the additional tags without any other other build triggers.

**Comment by matthewmcnew** [comment]
Does this accurately capture this issue @metacpp?

cc @ashwin-venkatesh

**Comment by ashwin-venkatesh** [comment]
> If this was implemented, we would need to figure out how handle updates to the additional tags without any other other build triggers.

I really appreciate the callout.

**Comment by matthewmcnew** [comment]
Closing with the introduction of `.spec.additionalTags`

**Comment by wdonne** [comment]
Isn't the consequence that for each image build the original tag will be set on it? With the `additionalTags` field all version tags would be put on every new image.
