### ISSUE TITLE
[Feature] Selectively propagate annotations from parent to child resources

### ISSUE THREAD

**Issue by ArieShout** [pivotal/kpack#32]
This is related to #8 .

When we get an update of the PBS custom resource via the K8s watch API, we need to extract some data to look up the corresponding object in our backend. Label value has too many restrictions so it's not suitable in this case.

> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

A good alternative is the annotation. To avoid conflicts with the system generated annotations, we may propagate the annotation values under some predefined (or configurable domain), such as:

```
Prefix: meta.build.pivotal.io/
meta.build.pivotal.io/key1 = blabla
meta.build.pivotal.io/some-other-key = blabla
```

**Comment by matthewmcnew** [comment]
#274 will propagate all annotations to  builds and pods.
