### ISSUE TITLE
release asset urls were changed + quirky

### ISSUE THREAD

**Issue by drnic** [pivotal/kpack#332]
v0.0.6 release

<img width="239" alt="Screen Shot 2020-03-20 at 10 21 47 am" src="https://user-images.githubusercontent.com/108/77126402-ae49d600-6a94-11ea-8e7a-80cb7e0c0fb0.png">

v0.0.7 release

<img width="281" alt="Screen Shot 2020-03-20 at 10 21 38 am" src="https://user-images.githubusercontent.com/108/77126409-b275f380-6a94-11ea-82bf-a63da5a479b1.png">

Could the release assets be re-released please?

Currently this has broken the `brew install starkandwayne/kubernetes/kpack-logs`:

```
$ brew upgrade
Updating Homebrew...
==> Upgrading 1 outdated package:
starkandwayne/kubernetes/kpack-logs v0.0.6 -> v0.0.7
==> Upgrading starkandwayne/kubernetes/kpack-logs v0.0.6 -> v0.0.7
==> Downloading https://github.com/pivotal/kpack/releases/download/v0.0.7/logs-v0.0.7-darwin.tgz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "kpack-logs"
Download failed: https://github.com/pivotal/kpack/releases/download/v0.0.7/logs-v0.0.7-darwin.tgz
```

(I've yanked v0.0.7 from our homebrew)

**Comment by matthewmcnew** [comment]
Good catch! It looks like there were still a few more quirks to work out in our automated tooling.  We updated [0.0.7](https://github.com/pivotal/kpack/releases/tag/v0.0.7) with proper names for the logs archives and also updated our automated tooling for the future. 

Could you check to see if the updated release works for you?

Note: We renamed logs-v***-darwin.tgz to  logs-v***-macos.tgz.

**Comment by drnic** [comment]
Thanks. I've now fixed the homebrew too.
