### ISSUE TITLE
When using DockerHub (within `cf-for-k8s`), building an application fails (in prepare step)

### ISSUE THREAD

**Issue by pivotaljohn** [pivotal/kpack#334]
## Overview

Release Integration is attempting to integrate `capi` using `kpack` for Cloud Native Buildpack support.

When using GCR as the backing image repository, the application builds and deploys, as expected.

However, when using DockerHub as the backing image repository for `kpack`, the prepare step fails, seemingly because the repository hostname is not parsed well.

## Versions

- [capi-k8s-release@f96d1d1](https://github.com/cloudfoundry/capi-k8s-release/tree/f96d1d1ded000f8dc102a6343e55dee67551aab3)
- kpack v0.0.6
- cnb image: `cloudfoundry/cnb:0.0.55-bionic`

## Steps to Reproduce

_Note: using `kpack` as an integrated component of `cf-for-k8s` (through `capi-k8s-release`)._

1. configure the `kpack` part of the `capi` "component" of `cf-for-k8s` to use DockerHub:
    `cf-values.yml`
    ```yaml
    ...
    kpack:
      registry:
        hostname: https://index.docker.io/v1/
        repository: relintdockerhubpushbot
        username: relintdockerhubpushbot
        password: ****
    ```
2. deploy `cf-for-k8s` which includes `kpack`
3. `cf push` an application
4. review the build pod init containers' logs (only the `prepare` container runs)
```console
$ kapp logs --app label:cloudfoundry.org/build_guid=6ad02e2a-5ce6-4866-adab-68e1b551738b

b26fcea7-2104-4119-aacf-3cf10fa095cf-build-1-4wg96-build-pod > prepare | prepare:main.go:62: Get https://https/v2/: dial tcp: lookup https on 10.0.48.10:53: no such host

```

### `hostname` appears to be properly plumbed through to relevant `kpack` annotation
We observe that the `hostname` specified in the `kpack` config (above) is rendered as the `build.pivotal.io/docker` annotation on the `cc-kpack-registry-auth-secret` Secret:

```console
$ kubectl get Secret cc-kpack-registry-auth-secret -n cf-system -o yaml
apiVersion: v1
data:
  password: ****
  username: ****
kind: Secret
metadata:
  annotations:
    build.pivotal.io/docker: https://index.docker.io/v1/
    kapp.k14s.io/identity: v1;cf-system//Secret/cc-kpack-registry-auth-secret;v1
    ...
  labels:
    kapp.k14s.io/app: "1584662988960675000"
    ...
  name: cc-kpack-registry-auth-secret
  namespace: cf-system
  resourceVersion: "16596850"
  selfLink: /api/v1/namespaces/cf-system/secrets/cc-kpack-registry-auth-secret
  uid: 9bacf9af-6a3f-11ea-948e-42010a800183
type: kubernetes.io/basic-auth
```

### GCR seems to work

When the same steps are performed, instead targeting a Google Container Repository (GCR) instance in the `kpack` portion of the `capi` config, the application deploys successfully.

----

Best way to reach us is at the [#cf-for-k8s](https://cloudfoundry.slack.com/archives/CH9LF6V1P) Slack channel.  Please tag @sai and @jtigger.  Thanks!

**Comment by matthewmcnew** [comment]
Hi @pivotaljohn,

The configured secret annotation looks correct for dockerhub. 

The `prepare:main.go:62: Get https://https/v2/: dial tcp: lookup https on 10.0.48.10:53: no such host` error seems to imply an invalid tag name. Could you share the tag on your image/build?

**Comment by jamespollard8** [comment]
I'm not sure exactly which tag you're referring to. I found an `IMAGE_TAG` on our `prepare` container that looks like:
`https://index.docker.io/v1/relintdockerhubpushbot/<build_guid>`

**Comment by matthewmcnew** [comment]
The tag should be on the image resource as `spec.tag` or on the build resource as `spec.tags`. I believe the `IMAGE_TAG` env var is equivalent to the build `build.spec.tags[0]`.

`https://index.docker.io/v1/relintdockerhubpushbot/<build_guid>` is invalid for dockerhub. It should be `relintdockerhubpushbot/<build_guid>`.

**Comment by jamespollard8** [comment]
Cool, thanks. We'll close this in favor of https://github.com/cloudfoundry/cf-for-k8s/issues/71 because it appears to not be a kpack issue.

**Comment by jamespollard8** [comment]
FWIW this has been fixed in cf-for-k8s
