### ISSUE TITLE
Image name length requirement

### ISSUE THREAD

**Issue by thephw** [pivotal/kpack#344]
# Image name length requirement

```
Reconcile error	{"error": "image name requirement: invalid label value: \"github-onspaceship-booster-rack-app-690156b7cf99c7093a1ec4fd77ae3327ff8921b8\": at key: \"image.build.pivotal.io/image\": must be no more than 63 characters"}
knative.dev/pkg/controller.(*Impl).handleErr
```

At this time we utilize the image name as a label on an image's builds so the image name must adhere to an image's name to a labels length constraint of 63 characters. 

# Context

We were working around an issue where we programmatically made an Image resource from a github org/repo name and a SHA. The programmatic creation of the image still succeeds, but the build does not due to the image name length requirement on the build tag. The error popped up within the logs of kpack controller. 

Not a hard workaround to check the name length and adjust before creating the image. However we could add some validation to the name length to throw an error at creation time of the image knowing how the downstream implementation works.

**Comment by dumez-k** [comment]
Fixed in [pr 640 ](https://github.com/pivotal/kpack/pull/640)

**Comment by mgibson1121** [comment]
Nice!  Accepting.
