### ISSUE TITLE
Rebase fails with images on gcr

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#392]
An Image configured with gcr creds for a private gcr image is able to build successfully when executing "regular" build but, appears to fail on rebase builds:

```
[rebase] ERROR: stack not defined on working image
```

Preliminary research showed that is is not able to access the previous image perhaps by being unable to load gcr credentials.

**Comment by djoyahoy** [comment]
This commit https://github.com/pivotal/kpack/commit/908282b410cac73e17b8ce4d6d6ba39f6f048bf1 erroneously removed the full path from dockercfg and dockerconfig secfets. I'll have a fix for this out soon.

**Comment by mgibson1121** [comment]
Tested and accepted this fix.
