### ISSUE TITLE
Changes to bindings in the image spec should result in a new build

### ISSUE THREAD

**Issue by ekcasey** [pivotal/kpack#396]
If I change the `build.bindings` section of my image spec (E.g. to add/remove a binding or even fix a typo in my `SecretRef`), a build should be triggered.

This won't solve the problem of a build triggering when the _contents_ of a binding change (#84), but it is also important to me as a user.

**Comment by matthewmcnew** [comment]
This makes sense. The lack of rebuilds was an oversight.
