### ISSUE TITLE
Introduce Application CRD

### ISSUE THREAD

**Issue by ShadowJonathan** [pivotal/kpack#414]
I'm proposing to introduce an `Application` CRD, which does two things:
- Hold a `ImageSpec` and a `DeploymentSpec`
- Update the `DeploymentSpec.image` value upon successful new build.

This creates a simple Continuous Deployment option pipeline on image build completion, and can small-scale app developers to rollout their applications.

(Maybe through a `hold` value, the application value can be held back)

**Comment by matthewmcnew** [comment]
Hi @ShadowJonathan, I like this idea!

Historically, we have avoided being opinionated how kpack images are deployed and allowed that to provided by external projects like https://github.com/projectriff. 

I could see us providing extensions like this "Application CRD" as an extension project to kpack.

**Comment by matthewmcnew** [comment]
Closing as this has gone stale. Please reopen if needed.
