### ISSUE TITLE
Prepare step should error when a source blob is inaccessible or invalid

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#426]
## What Happens
Currently, when an inaccessible or invalid blob url is provided to the prepare step the prepare step will complete without error and the build will fail when detect runs against an empty workspace. 

This is because when the prepare step fetches a provided source blob url it will attempt to unpack the blob even if a non 200 status code is returned. This is additionally problematic because the fetch will [ignore unexpected file types](https://github.com/pivotal/kpack/blob/e075180cb39b2898928973d0469fba9fc2172c4e/pkg/blob/fetch.go#L48) and exit with a success. 

## Reproduce
* Create an image with a `spec.source.blob.url` of something that does not exist like: `https://storage.googleapis.com/INVALID.jar`
* See this errored build: 

```
===> PREPARE
Loading secret for "****" from secret "***" at location "/var/build-secrets/***"
Successfully downloaded storage.googleapis.com/INVALID.jar in path "/workspace"
===> DETECT
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
```

**Comment by matthewmcnew** [comment]
Originally found by @trisberg .

**Comment by tylerphelan** [comment]
Acceptance steps:

1. Create 2 Images of blob source-type with blob urls that are
- Unaccessible
- Not the expected type (like a text file)

See the errors in the `PREPARE` step.

Happy to help with this.
