### ISSUE TITLE
unable to fetch remote builder image

### ISSUE THREAD

**Issue by riponbanik** [pivotal/kpack#428]
When use  kubectl get clusterbuilder default -o yaml, the error shows as below, it is to be mentioned here that there is enterprise proxy but docker daemon is whitelisted to accept the ssl.

status:
  conditions:
  - lastTransitionTime: "2020-06-29T23:25:25Z"
    message: 'unable to fetch remote builder image: Get "https://gcr.io/v2/": x509:
      certificate signed by unknown authority'
    status: "False"
    type: Ready

docker pull works on the node -

docker pull gcr.io/paketo-buildpacks/builder:base

**Comment by matthewmcnew** [comment]
Hi @riponbanik, Unfortunately, we don't have a good answer for this at the moment but, the complication of providing a custom CA cert for kpack is a [known issue](https://github.com/pivotal/kpack/issues/207). 

The only workaround available is a bit involved. You will need to add the ca cert for your enterprise proxy to the kpack controller image and to the `gcr.io/paketo-buildpacks/builder:base` image or use a CustomBuilder and add it to the Build Image.
