### ISSUE TITLE
Unable to fetch remote run image

### ISSUE THREAD

**Issue by evilrussian** [pivotal/kpack#430]
Hi. I have not direct access to internet - only corporate docker-proxy.

When i changed images of controller and others to our registry i had this message:
```
kubectl describe clusterbuilders.build.pivotal.io default
...
Status:
  Conditions:
    Last Transition Time:  2020-07-02T07:15:19Z
    Message:               unable to fetch remote builder image: Get "https://registry.test.ru/v2/": x509: certificate signed by unknown authority
```
Situation like in issue #428 

After i had rebuild images: controller, BUILD_INIT_IMAGE and image for ClusterBuilder.yaml
In this images i added CA ssl certs in pem format into /etc/ssl/certs.

Now i have this message:
```
kubectl describe clusterbuilders.build.pivotal.io default
...
Status:
  Conditions:
    Last Transition Time:  2020-07-02T10:42:10Z
    Message:               unable to fetch remote run image: Get "https://gcr.io/v2/": dial tcp 64.233.162.82:443: connect: connection refused
    Status:                False
    Type:                  Ready
  Observed Generation:     2
```
It tries to fetch image with direct internet access. Can you add defining of run image in controller's env? Like defining BUILD_INIT_IMAGE or LIFECYCLE_IMAGE.

It's very important for corporate users.

**Comment by tylerphelan** [comment]
@evilrussian To use your own registry without access to the internet, you can create a [Builder](https://github.com/pivotal/kpack/blob/master/docs/builders.md) with the run, build, and buildpackage images coming from your registry.

It may be easier for this use case to create a [CustomBuilder](https://github.com/pivotal/kpack/blob/master/docs/custombuilders.md) which allows you to specify the stack and buildpackage images with kubernetes manifests.

**Comment by evilrussian** [comment]
> to use your own registry without access to the internet, you can create a [Builder](https://github.com/pivotal/kpack/blob/master/docs/builders.md) with the run, build, and buildpackage images coming from your registry.

 the doc https://github.com/pivotal/kpack/blob/master/docs/builders.md tells me that i can define only builder image 

I did it:
```
apiVersion: build.pivotal.io/v1alpha1
kind: ClusterBuilder
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"build.pivotal.io/v1alpha1","kind":"ClusterBuilder","metadata":{"annotations":{},"name":"default"},"spec":{"image":"registry.test.ru/docker/kpack-images/builder:base"}}
  creationTimestamp: "2020-07-02T07:00:25Z"
  generation: 2
  name: default
  resourceVersion: "27452798"
  selfLink: /apis/build.pivotal.io/v1alpha1/clusterbuilders/default
  uid: 5cbc9670-bb2d-4a51-a037-16218bba7eb2
spec:
  image: registry.test.ru/docker/kpack-images/builder:base
  updatePolicy: polling
status:
  conditions:
  - lastTransitionTime: "2020-07-02T14:44:20Z"
    message: 'unable to fetch remote run image: Get "https://gcr.io/v2/": dial tcp
      64.233.162.82:443: connect: connection refused'
    status: "False"
    type: Ready
  observedGeneration: 2
  stack: {}
```
but it trying to get run image from internet. How i can define run image?

**Comment by matthewmcnew** [comment]
How did you create `registry.test.ru/docker/kpack-images/builder:base`? If you created it with pack you can update the stack run-image. However, if you only relocated an existing builder to `registry.test.ru` it is likely easier to use a CustomBuilder as @tylerphelan suggested.
