### ISSUE TITLE
Fix execute permission for the Maven wrapper

### ISSUE THREAD

**Issue by ArieShout** [pivotal/kpack#445]
This should be a problem related to the [build-system-cnb](https://github.com/cloudfoundry/build-system-cnb) but that repository is archived.

If we archive the source code to a tar.gz ball in Windows, it's likely we will lost the execute permission bit of the Maven wrapper (mvnw).

When kpack extracts the archive, it just check whether the file `mvnw` exists, but doesn't check if it's executable. During the build, we see the following error:

```
Pivotal Build System Buildpack 1.0.97
  fork/exec /workspace/mvnw: permission denied
```

We may need either
1. skip `mvnw` if it's not marked as executable (in build-system-cnb)
2. or, set the execution permission of the file before we start the build. (in kpack prepare phase)

**Comment by matthewmcnew** [comment]
Hi @ArieShout, I believe that question would be best asked on the https://github.com/paketo-buildpacks/maven buildpack. 

Thanks!

**Comment by ArieShout** [comment]
Thanks Matt, just raised this to https://github.com/paketo-buildpacks/maven/issues/6

**Comment by ArieShout** [comment]
Hi @matthewmcnew ,

We did some more analysis on the issue. We can confirm that the `mvnw` in the source archive prepared by the Azure CLI has the correct executable permission (0755). However, when the archive is extracted by the kpack prepare phase, the file permission was reset to the shell default (0644), which leads to the followed error in Maven build.

While the Maven buildpacks already has a workaround, I think we should fix this from kpack prepare phase. Otherwise if the build depends on some other executable file, we may fail again and it's not trivial to prepare workaround for various cases.

**Comment by matthewmcnew** [comment]
@ArieShout Do you have a sample blob you could share to test with?

**Comment by ArieShout** [comment]
@matthewmcnew sent you the file & K8s config through email.
