### ISSUE TITLE
Build status should show up as ImagePullBackoff when a container has an ImagePullBackoff error

### ISSUE THREAD

**Issue by tylerphelan** [pivotal/kpack#457]
**Details**

When one of the containers (Detect, Build, etc) is erroring due to ImagePullBackoff, the Build will continue running for a significant amount of time and the Build status will return as Unknown.

This can show up for many reasons but one use case is Builds not having access to ClusterBuilders (previously CustomClusterBuilders).

To improve the experience, we should radiate this error to the user via the status.

**Acceptance Criteria**

When my Build is having ImagePullBackoff errors
Then I see ImagePullBackoffError in the Build status

**Comment by matthewmcnew** [comment]
I am going to close this as it was resolved with: https://github.com/pivotal/kpack/pull/461
