### ISSUE TITLE
Build resources with `Succeeded` `false` and  message `pods "POD_NAME" already exists`

### ISSUE THREAD

**Issue by matt-royal** [pivotal/kpack#460]
The CAPI team occasionally sees CI failures during a `cf push`, where the staging output indicates that staging succeeded, but then the push command hangs and eventually times out. 

When we've inspected our cf-api-controller logs after this issue occurs, we see that the `build` resource gets into an unexpected state. This prevents us from updating the CC build and marking it as successful or failed. Here's an example build status:

```
{
  "observedGeneration": 1,
  "conditions": [
    {
      "type": "Succeeded",
      "status": "False",
      "lastTransitionTime": "2020-07-24T18:16:15Z",
      "message": "pods \"8c5af030-d3ea-4455-9b4e-c95ef93a1fea-build-1-pbvzb-build-pod\" already exists"
    }
  ]
}
```

Currently we take no action in this case, which leads to the hanging behavior described above. We've discussed changing our behavior to either 1) marking the CC build as failed, or 2) requeueing the build update event until this "pods already exists" failure becomes a success or a different error.

We're hoping that you can provide further context about the expected lifecycle of the "build" resource to help us make the right decision. Alternately, if this is a bug on your end then perhaps you can resolve this issue for us entirely. Here are some questions to help us:

1. Is this "pods already exists" state one that you expect?
1. If this is an expected state, is it a terminal state or do you expect it to eventually transition into a different terminal state? If it's not a terminal state, why set it at all? You could instead wait until you reach the terminal success or failure state, and only then update the `build` resource. This would solve the hanging problem we're seeing.
1. If this isn't an expected state, do you have a theory about what might be causing it? What additional information can we provide to help you find it? Unfortunately we haven't found a way to reproduce this issue reliably, but we can capture logs and other information the next time it occurs on our CI.

Here are some related issues we found that may help:
- https://github.com/pivotal/kpack/issues/364
- https://github.com/cloudfoundry/capi-k8s-release/issues/27
- https://github.com/cloudfoundry/capi-k8s-release/issues/60

Thanks!
Matt + @njbennett

**Comment by cwlbraa** [comment]
> If this is an expected state, is it a terminal state or do you expect it to eventually transition into a different terminal state?

in cf-for-k8s, we've seen multiple instances of this failure state being terminal: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1596826175288300
