### ISSUE TITLE
kpack (specifically cf-for-k8s) integration with ECR

### ISSUE THREAD

**Issue by aegershman** [pivotal/kpack#477]
Are there any thoughts on the future of being able to incorporate kpack (specifically kpack in the context of `cf-for-k8s`) with ECR?

**background**-- I'm interested in using ECR as an image registry for kpack to use in the context of `cf-for-k8s`, [however according to some slack searches](https://buildpacks.slack.com/archives/CD61YAG69/p1592933830260500?thread_ts=1592925820.258700&cid=CD61YAG69) I'm getting the impression ECR doesn't currently follow or implement capabilities for kpack to use ECR in the same way it does dockerhub, Azure Container Registry, Google Container registry, artifactory, harbor, all that good stuff.

... I've also tried configuring cf-for-k8s to use an ECR repository for images, and the CustomBuilder threw errors due to being unable to create a repository grouping on ECR (e.g. a "repo" on dockerhub, a "repo/library" on harbor, etc.); it appears maybe the same concepts don't exist with ECR (apologies I don't have specific logs, this is from memory)

Apologies if this question more-so belongs in the cloudfoundry/cf-for-k8s repository. 

Thanks for folks' time 👍

**Comment by matthewmcnew** [comment]
Hi @aegershman, we have not investigated ECR recently and need to figure out exactly where ECR is noncompliant. In the meantime, This might be a better issue to ask in the buildpacks slack itself.

**Comment by aegershman** [comment]
No worries, thank you 👍  closing for tidyness
