### ISSUE TITLE
Improved build logs for fetching source

### ISSUE THREAD

**Issue by sukhil-suresh** [pivotal/kpack#498]
[Reported by @mgbrodi]

This was observed in a kpack environment, where the network was slow
 
**Problem:** after a build is triggered for an image and the build log informs the user about using a credential for a repo when the network is slow, the build log remains stuck for a long while when the source code is being fetched from a git repository.

The user is left confused as to whether the git secret was valid or not? And if fetching the git repo has begun. 

The **expectation** is better logging of events for a build. Ideally, the logs inform the user:
- if the secret was validated
- when source fetching has begun
- and, If possible, a progress indicator for the source code fetching

If multiple creds match the source, make it obvious which one is being used.

Also, verify if the logging improvement is applicable for other sources resolvers (besides git).

Possibly related: [Configurable log levels for a kpack build #391](https://github.com/pivotal/kpack/issues/391)

**Comment by sampeinado** [comment]
"im going to clone the repo, it may take a while" might be all we need here

**Comment by sampeinado** [comment]
A screenshot of what the logs look like at different stages of output would be super helpful!

**Comment by sampeinado** [comment]
spinner ?!

**Comment by mgibson1121** [comment]
This story passes acceptance
