### ISSUE TITLE
Report status details of latest CNBBuild on CNBImage

### ISSUE THREAD

**Issue by scothis** [pivotal/kpack#5]
When I create a CNBImage, I'd like to know the status of the build (and ideally the most recently built image name). Currently there is no meaningful status reflected on the CNBImage resource other than the name of the latest CNBBuild resource.

As a user, I should only need to interact with the resource that I created in order to get a high level summary of the current status. Forcing me to lookup another resource that I didn't create violates the principle of least knowledge.

**Comment by matthewmcnew** [comment]
Closing as we provide the latestImage on the Image resource and will report Ready=Unknown while building.
