### ISSUE TITLE
Add reason-message and reasons diff to build logs 

### ISSUE THREAD

**Issue by sampeinado** [pivotal/kpack#513]
[RFC](https://github.com/sampeinado/kpack/blob/master/rfcs/0002-reason-message-diff.md)
[Thread on PR](https://github.com/pivotal/kpack/pull/492)

Check out the mockups in the RFC !

**Comment by mgibson1121** [comment]
@sukhil-suresh Not seeing the reason diff in the status output on staging using the latest kp binary I could find (`0.1.4.build.8)`.  As I type, it strikes me that this is probably the problem as that binary was published on Dec. 8.  I've been getting the binaries from here https://console.cloud.google.com/storage/browser/kp-public;tab=objects?project=cf-build-service-dev-219913&prefix=&forceOnObjectsSortingFiltering=false&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22)).  Is there a better place?

**Comment by mgibson1121** [comment]
This story passes acceptance.
