### ISSUE TITLE
kpack can create windows images

### ISSUE THREAD

**Issue by tylerphelan** [pivotal/kpack#545]
[RFC](https://github.com/pivotal/kpack/blob/master/rfcs/0003-windows-images.md)

**1. kpack supports creating windows builders**

When a Builder or ClusterBuilder is created using a windows stack and windows buildpackages, kpack-controller must create a windows builder using the windows lifecycle image.

Notes
- Image os is determined by the image [os property](https://github.com/opencontainers/image-spec/blob/master/config.md#:~:text=os%20string).
- [pack cli](https://github.com/buildpacks/pack) has prior art for this
- Error when stack images are mixed os
- kpack-controller may use a new environment variable `WINDOWS_LIFECYCLE_IMAGE` to reference the windows lifecycle image

**2. kpack can create windows images**

When a user creates an image using a windows builder, it should create a windows image

Notes:
- When a Build is created using a windows Builder or ClusterBuilder image it should create a build pod using windows "helper" image(s) and it should be scheduled on windows nodes
- Scheduling build pods on windows nodes will user the node selector:
```
nodeSelector:
    kubernetes.io/os: windows
```

- Image os is determined by the image [os property](https://github.com/opencontainers/image-spec/blob/master/config.md#:~:text=os%20string).
- Assume users will only use Windows Server 2019 LTSC

**Comment by mgibson1121** [comment]
This story passes acceptance.
