### ISSUE TITLE
Use value from secrets in environment variables

### ISSUE THREAD

**Issue by cirocosta** [pivotal/kpack#554]
Hi!

While going through the docs and the types for the Build CRD, I got the impression that given that the `corev1.EnvVar` type is used, I could leverage `valueFrom: {secretKeyRef: <>}` to fill that variable with a value from a secret, but as those references are never resolved before the marshalling (https://github.com/pivotal/kpack/blob/3b1a44a1b15c8e0036e054718a9edd1b0695ac00/pkg/apis/build/v1alpha1/build_pod.go#L98-L101), we end up with just the pure json representation of it:

```
      - name: PLATFORM_ENV_VARS
        value: '[{"name":"FOO","value":"bar},{"name":"CAZ","valueFrom":{"secretKeyRef":{"name":"zaz","key":"zaz"}}]'
```

_(^ from the pod spec)_

It makes sense to not have the values in plain text there in the json, but I wonder if it'd be interesting to have those refs dereferenced when writing them down to `platform/env/<env_key>`.

I don't _really_ have a use-case for it that can't be covered through bindings, but, it seemed a bit confusing to me to not have that ability given the type used - perhaps the action here would be an update in the docs?

thank you!

**Comment by matthewmcnew** [comment]
It seems reasonable to expect the value from format to be accepted.

**Comment by matthewmcnew** [comment]
Closed in https://github.com/pivotal/kpack/issues/554
