### ISSUE TITLE
proxy support in BuildPod

### ISSUE THREAD

**Issue by aad** [pivotal/kpack#567]
We are using kpack (as part of cf-for-k8s) behind corporate firewall. We got below errors from `logs` when we try create the images (cf push). It seems that the BuildPod doesn't honor the proxy settings in the kpack-controller. [Here in build_pod.go](https://github.com/pivotal/kpack/blob/v0.1.2/pkg/apis/build/v1alpha1/build_pod.go#L155) and [here in build-init/main.go](https://github.com/pivotal/kpack/blob/v0.1.2/cmd/build-init/main.go#L88). Any plan to support the proxy or any suggestions to work around the error in all the BuildPod steps?

```
logs -namespace cf-workloads-staging -image a8aa727d-4576-46f7-880f-15280f3ea79d
===> PREPARE
Loading secret for "https://index.docker.io/v1/" from secret "cc-kpack-registry-auth-secret-ver-1" at location "/var/build-secrets/cc-kpack-registry-auth-secret-ver-1"
Error verifying write access to "myaccount/a8aa727d-4576-46f7-880f-15280f3ea79d": Get "https://index.docker.io/v2/": dial tcp: lookup index.docker.io on 10.100.0.10:53: no such host
^C
```

**Comment by matthewmcnew** [comment]
Hi @aad, We don't currently have support in kpack to provide a http_proxy for the build. This is something we might consider in the future. Perhaps as an [rfc](https://github.com/pivotal/kpack/tree/master/rfcs)?

However, in the meantime a possible workaround would be to use the [cert injection webhook](https://github.com/vmware-tanzu/cert-injection-webhook) to provide an http/https proxy to kpack builds.

**Comment by aad** [comment]
@matthewmcnew, Thanks for the advice! We are still in early stage to explore options and we don't have a strong reason to use public registries via proxy. cert inject one is interesting and I'll have a try.

Please feel free to close the issue.

**Comment by aad** [comment]
i  wanted to update that cert injection webhook works well injecting certs into cf-api-worker in  our case
