### ISSUE TITLE
Step Stage 6(EXPORT)  exited with code 246

### ISSUE THREAD

**Issue by manshaaazar** [pivotal/kpack#591]
When kpack reaches at step stage 6 EXPORT, it sends back exit code 246, 

   // below is the pod's description //
  Conditions:
    Last Transition Time:  2021-01-05T20:35:18Z
    Status:                False
    Type:                  Succeeded
  Observed Generation:     1
  Pod Name:                f-image-build-1-t9bw6-build-pod
  Stack:
  Step States:
    Terminated:
      Container ID:  containerd://4e976e8ad23149b5f708da3ba91aa1fba233d7c553917e8a3bb2ee1802da3a35
      Exit Code:     0
      Finished At:   2021-01-05T20:20:46Z
      Reason:        Completed
      Started At:    2021-01-05T20:20:12Z
    Terminated:
      Container ID:  containerd://b71effae359e0c47d9c92d53956856d8dde9d33d1ba573ba07b07a597083d95b
      Exit Code:     0
      Finished At:   2021-01-05T20:21:03Z
      Reason:        Completed
      Started At:    2021-01-05T20:20:54Z
    Terminated:
      Container ID:  containerd://98407b0d02647561d582a9e7d28d82205787895a14a7f752ee03c6354aae74be
      Exit Code:     0
      Finished At:   2021-01-05T20:21:18Z
      Reason:        Completed
      Started At:    2021-01-05T20:21:09Z
    Terminated:
      Container ID:  containerd://b69457858bf5f8216070628fd0eac45c70ff36666e9aa7bef52f0786178c1426
      Exit Code:     0
      Finished At:   2021-01-05T20:21:25Z
      Reason:        Completed
      Started At:    2021-01-05T20:21:25Z
    Terminated:
      Container ID:  containerd://329f4b6652c974391ef2e52392e36ff9d6a80c9301d3a82faea64efc13a57273
      Exit Code:     0
      Finished At:   2021-01-05T20:23:01Z
      Reason:        Completed
      Started At:    2021-01-05T20:21:31Z
    Terminated:
      Container ID:  containerd://a5876904c5158c0091e9e227bbbf249be51d8043e40674f27a9bc4f86d33e171
      Exit Code:     246
      Finished At:   2021-01-05T20:35:14Z
      Reason:        Error
      Started At:    2021-01-05T20:23:24Z
  Steps Completed:
    prepare
    detect
    analyze
    restore
    build
    export
Events:  <none>

**Comment by matthewmcnew** [comment]
Hi @manshaaazar, 
Could you share the logs from the build?

**Comment by manshaaazar** [comment]
===> EXPORT
Reusing layers from image 'index.docker.io/manshaehsan/knight@sha256:0c83a425e071a43e1b576a28e2c24e0f8f6322bfbd412e5c52c469ac39bf450a'
Adding layer 'paketo-buildpacks/node-engine:node'
Adding layer 'paketo-buildpacks/npm-install:modules'
Adding layer 'paketo-buildpacks/npm-install:npm-cache'
Adding 1/1 app layer(s)
Adding layer 'launcher'
Adding layer 'config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
*** Images (sha256:91e8c1e21ee20e13aefba66984c72a2c2df45236c2aa2deecc1c0334de5e4bb9):
      manshaehsan/knight - PATCH https://index.docker.io/v2/manshaehsan/knight/blobs/uploads/047caf07-0ffa-431e-ae30-d08bb71dcbcf?_state=REDACTED: unsupported status code 504; body: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>


      index.docker.io/manshaehsan/knight:b1.20210108.162718 - PATCH https://index.docker.io/v2/manshaehsan/knight/blobs/uploads/d4d898b6-3569-444e-be12-5985803ea153?_state=REDACTED: unsupported status code 504; body: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>


ERROR: failed to export: failed to write image to the following tags: [manshaehsan/knight: PATCH https://index.docker.io/v2/manshaehsan/knight/blobs/uploads/047caf07-0ffa-431e-ae30-d08bb71dcbcf?_state=REDACTED: unsupported status code 504; body: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

],[index.docker.io/manshaehsan/knight:b1.20210108.162718: PATCH https://index.docker.io/v2/manshaehsan/knight/blobs/uploads/d4d898b6-3569-444e-be12-5985803ea153?_state=REDACTED: unsupported status code 504; body: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

**Comment by tylerphelan** [comment]
@manshaaazar this happens consistently with builds?

**Comment by manshaaazar** [comment]
@tylerphelan 
yes happening in every build

**Comment by tylerphelan** [comment]
@manshaaazar this seems to be an issue with the registry. have you tried using a different dockerhub repository or a different registry like GCR?

**Comment by manshaaazar** [comment]
yes i tried with azure registry and it worked well.

**Comment by manshaaazar** [comment]
@tylerphelan  thank you very much
