### ISSUE TITLE
The lifecycle image should be configurable

### ISSUE THREAD

**Issue by tylerphelan** [pivotal/kpack#594]
RFC: https://github.com/pivotal/kpack/pull/560 (soon to be merged)

**Problem:**
Users have no way of upgrading the lifecycle image without upgrading the kpack release

**Criteria:**
1. An update to `ConfigMap` `lifecycle-image.data.image` results in builders being recreated
2. The `ConfigMap` `lifecycle-image.annotations.platformApiVersions` should be validated that kpack supports all of the platform apis 

**Actions:**
- The ConfigMap `lifecycle-image` should no longer be mounted in the kpack-controller
- kpack should watch for changes to ConfigMap `lifecycle-image` in the `kpack` namespace
- Updates to the ConfigMap `lifecycle-image.data.image` value should result in builders being recreated
- `lifecycle-image.annotations.platformApiVersions` is a new optional field containing space-separated values in the form of X.X
- if `lifecycle-image.annotations.platformApiVersions` contains no versions supported by kpack, the ConfigMap should fail validation

Notes:
- This will NOT fan out to all images. Builds will only use the new lifecycle on the next build scheduled normally

**Comment by matthewmcnew** [comment]
Perhaps `lifecycle-image.data.platformApiVersions` should be an annotation to prevent implying that is a functional configuration attribute?

**Comment by mgibson1121** [comment]
Moving to accepted and will accept the user facing issue https://github.com/vmware-tanzu/kpack-cli/issues/142
