### ISSUE TITLE
Intelligently apply tolerations to windows pods

### ISSUE THREAD

**Issue by tomkennedy513** [pivotal/kpack#604]
We found that IaaS's seem to be adding taints to windows nodes to prevent pods being scheduled there and then using a webhook in GKE's case or instructing users to manually add a toleration to every pod in TGKI so that they can be scheduled on windows nodes. The problem lies with the fact that different IaaS's use different taints on windows nodes so there isn't a one size fits all toleration we can add to all windows builds. We also want to be very conservative with the tolerations we apply. To do this we get a list of all windows nodes before scheduling a build and look at the node taints. If they are all the same, we apply matching tolerations for all the taints on the windows nodes. If they are not equal, we don't do anything and the pod will be left unschedulable. We think that this will be the most naive approach that solve our problem.

**Comment by matthewmcnew** [comment]
@tomkennedy513 Can you document our strategy here and why?
