### ISSUE TITLE
[Feature] Support credential helper in build-pod to export the image to ACR

### ISSUE THREAD

**Issue by metacpp** [pivotal/kpack#622]
User scenario: run the kpack on Azure Kubernetes Cluster to build the source code into OCI image then export it to Azure container registry.

Today the build pod will use docker secret as the authentication way to export image, can we support credential helper to use managed identity to be authed to access the container registry ?

**Comment by tylerphelan** [comment]
this should be fixed with https://github.com/pivotal/kpack/pull/959
