### ISSUE TITLE
Switch git library to git2go

### ISSUE THREAD

**Issue by tylerphelan** [pivotal/kpack#626]
RFC with more context: https://github.com/pivotal/kpack/pull/620

This will help solve the issue with azure devops: https://github.com/pivotal/kpack/issues/213

Notes:
- The amazing [flux implementation](https://github.com/fluxcd/source-controller/tree/d1ee61844d3a51987708bc365d44b3e88cbdcdb9/pkg/git/libgit2)
- git2go relavent apis:
  - [SSH Auth](https://github.com/libgit2/git2go/blob/master/credentials.go#L164)
  - [Fetch](https://github.com/libgit2/git2go/blob/master/remote.go#L890)
  - [Create remote](https://github.com/libgit2/git2go/blob/master/remote.go#L540)
- [libgit2](https://libgit2.org/) (windows supported)

**Comment by tylerphelan** [comment]
Open question: how to run on windows

**Comment by matthewmcnew** [comment]
Open PR: https://github.com/pivotal/kpack/pull/636
