### ISSUE TITLE
Churn bug when clusterstack run image digest is out of date with tagged run image

### ISSUE THREAD

**Issue by dumez-k** [pivotal/kpack#641]
When clusterstack run image is not fully qualified and is instead a soft pointer like `paketo-buildpacks/run` and the last reconcile of the clusterbuilder is out of date with the current tagged image on dockerhub, then an infinite number of builds are scheduled as kpack is trying to get a build to produce an image with the old run image. 

To reproduce:
Create a stack with spec.image.run-image pointing to a run image with tag
Create a builder and build with this stack
Update image ref by tag
Trigger a new build

Here are also some other [reproduction steps](https://github.com/wind57/kpack) reported in issue #979

**Comment by dumez-k** [comment]
Possible options: 

1) Create builders and clusterbuilders with fully qualified run image refs
1) Specify the run image with fully qualified digest that should be used for builds and rebases

**Comment by zhoufenqin** [comment]
I also meet the problem and any update on this issue? which kpack version will fix this? it seems the issue has already last for a long time

**Comment by jjbustamante** [comment]
I would like to work on this issue, not sure if I have all the knowledge but I can give it a shot. 😃

**Comment by zhoufenqin** [comment]
> not sure if I have all the knowledge but I can give it a shot.

Thank you @jjbustamante :)
I added some details, once the cluster runImage is updated and the builder configured stack runImage hasn't been updated, multiple builds will be triggered. The `image.kpack.io/reason` is `STACK` or `CONFIG, STACK`
```
> k get build -l image.kpack.io/image=default.fenzho-0523 --sort-by='{.metadata.creationTimestamp}' -o go-template='{{range .items}} {{.metadata.creationTimestamp}} {{.metadata.name}} {{.metadata.resourceVersion}} {{index .metadata.annotations "image.kpack.io/reason"}} {{index .metadata.labels "image.kpack.io/imageGeneration"}} &{{end}}' | tr '\&' '\n'
 2022-05-25T03:16:03Z default.fenzho-0523-build-1 4203472 CONFIG 1
 2022-05-25T03:17:27Z default.fenzho-0523-build-2 4203527 STACK 1
 2022-05-25T03:17:33Z default.fenzho-0523-build-3 4203575 STACK 1
 2022-05-25T03:17:37Z default.fenzho-0523-build-4 4203617 STACK 1
 2022-05-25T03:17:41Z default.fenzho-0523-build-5 4203662 STACK 1
 2022-05-25T03:17:44Z default.fenzho-0523-build-6 4203707 STACK 1
......
......
```
![Pasted Image at 2022_05_25_15_11 pm](https://user-images.githubusercontent.com/8765864/173983182-b6837ca5-e475-47f4-bdf5-fea864cee6dd.png)
<img width="1079" alt="Pasted Image at 2022_05_25_15_11 pm (1)" src="https://user-images.githubusercontent.com/8765864/173983207-d9fd23e4-51fb-430e-b5c7-80381642bc04.png">

**Comment by zhoufenqin** [comment]
Hi @jjbustamante , any update on this issue? Which kpack version will fix this?

**Comment by jjbustamante** [comment]
Hi @zhoufenqin I wasn't able to work on this last week, but, my plan is to do it this week. I will keep everybody up to date.

**Comment by matthewmcnew** [comment]
Thanks for picking this up @jjbustamante!  For context for anyone that may run into this in the meantime, This will only occur when a tag is used in the ClusterStack spec. To resolve the issue specify stack images with the complete sha256 digest and update the ClusterStack resource when a new image should be used.

**Comment by jjbustamante** [comment]
### Update

I tried to reproduce the error today, but I wasn't able to. I think the following steps:

1. I installed kpack on a local docker kubernetes cluster
2. I followed the steps in the [tutorial](https://github.com/pivotal/kpack/blob/main/docs/tutorial.md) page
3. I have a registry in google cloud.

My stack configuration has the following

```yaml
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base641
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "gcr.io/cnb-playground/my-run-image"
```

Where the `gcr.io/cnb-playground/my-run-image` was created using the following Dockerfile

```
FROM paketobuildpacks/run:base-cnb
```

Once the Petclinic application was built, I updated the dockerfile with the following:

```
FROM paketobuildpacks/run:base-cnb
RUN mkdir -p /tmp/foo
````

Then, I tagged and pushed this image into my GCR registry, a new build was scheduled by kpack but it finished correctly

<img width="1421" alt="Screen Shot 2022-07-06 at 5 08 09 PM" src="https://user-images.githubusercontent.com/1181799/177653134-12cda825-19ba-4de1-99a7-275b807fdc1e.png">

If I am not mistaken,  it is updating the ClusterStack reference to the run-image right?

**Comment by zhoufenqin** [comment]
@jjbustamante  it always happened when a new build is triggered manually but the related builder runImage hasn't been updated (not waiting kpack to trigger the new build with "Build Reason: STACK"  ). Do you check the builder runImage when triggering a new build after updating the cluster stack? And whether the clusterstack runtime image in k8s has already been updated or not?
![image](https://user-images.githubusercontent.com/8765864/177668486-cc2e4300-4cdc-41be-816e-c6223159041b.png)

**Comment by jjbustamante** [comment]
Thanks @zhoufenqin,

I managed to reproduce it, triggering the new build right after I pushed my run-image. I will try to check the code tomorrow! 

```
➜  kpack kubectl get build -l image.kpack.io/image=tutorial-image-641 --sort-by='{.metadata.creationTimestamp}' -o go-template='{{range .items}} {{.metadata.creationTimestamp}} {{.metadata.name}} {{.metadata.resourceVersion}} {{index .metadata.annotations "image.kpack.io/reason"}} {{index .metadata.labels "image.kpack.io/imageGeneration"}} &{{end}}' | tr '\&' '\n'

 2022-07-06T21:32:50Z tutorial-image-641-build-1 21375 CONFIG 1
 2022-07-06T21:51:18Z tutorial-image-641-build-2 21996 STACK 1
 2022-07-06T21:53:21Z tutorial-image-641-build-3 22288 TRIGGER 1
 2022-07-06T22:00:46Z tutorial-image-641-build-4 43907 STACK 1
 2022-07-07T01:48:01Z tutorial-image-641-build-5 44168 TRIGGER 1 <--- I triggered this one
 2022-07-07T01:49:06Z tutorial-image-641-build-6 44242 STACK 1    <--- Loop begins
 2022-07-07T01:49:23Z tutorial-image-641-build-7 44321 STACK 1
 2022-07-07T01:49:40Z tutorial-image-641-build-8 44397 STACK 1
 2022-07-07T01:49:57Z tutorial-image-641-build-9 44476 STACK 1
 2022-07-07T01:50:16Z tutorial-image-641-build-10 44488 STACK 1
```

**Comment by matthewmcnew** [comment]
Yes, I think that is correct. Instead of using the fetched information on the builder which is an intentional floating pointer we should pass in the resolved builder run image when we have it. I think this will require that we specify the run image on the build resource.

**Comment by jjbustamante** [comment]
### Update

Well, based on @matthewmcnew comments, I just did the following quick changed

<img width="1154" alt="Screen Shot 2022-07-07 at 5 34 24 PM" src="https://user-images.githubusercontent.com/1181799/177882641-5f9a716f-2925-432f-8d6e-56876cabb8b2.png">

Then I deployed in my local cluster and triggered a build and issue was gone. I tested the following two scenarios:
- Triggered a build just right after I updated my run-image
- I updated my run-image and wait for the stack cluster build to run.

Both cases, were fine. 

My GCR registry

![Screen Shot 2022-07-07 at 5 45 50 PM](https://user-images.githubusercontent.com/1181799/177884492-9672cc87-2d73-4e2a-a69b-4c701b0d4562.png)

This is the final pod's state

<img width="1754" alt="Screen Shot 2022-07-07 at 5 45 12 PM" src="https://user-images.githubusercontent.com/1181799/177884138-b29179d9-859f-44e4-b80e-cc04b413aa63.png">

#### Build-2

Manual triggered build
<img width="890" alt="Screen Shot 2022-07-07 at 5 45 32 PM" src="https://user-images.githubusercontent.com/1181799/177884458-9bad6902-c922-412a-8c84-d10345f4a798.png">

#### Build-3
ClusterStack build triggered by kpack

<img width="1749" alt="Screen Shot 2022-07-07 at 5 46 17 PM" src="https://user-images.githubusercontent.com/1181799/177884572-38f91bd7-7cad-4d01-a484-bf933d5fa5d7.png">

#### Build-4
ClusterStack build triggered by kpack after I updated again my run-image

<img width="1746" alt="Screen Shot 2022-07-07 at 5 46 30 PM" src="https://user-images.githubusercontent.com/1181799/177884606-53411bc8-26a7-4708-9dc6-fdcfd3294389.png">

**Comment by tylerphelan** [comment]
option: enforce fully qualified stack images via validation?
