### ISSUE TITLE
Image Build is failing at the DETECT step 

### ISSUE THREAD

**Issue by KasiviswanadhPasam** [pivotal/kpack#651]
We are following the same procedure mentioned in the Tutorials.md, but the Image build is failing. The kubectl describe pod POD_NAME output shows the below error: 
Warning  Failed     5m19s  kubelet, minikube  Error: failed to start container "detect": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/cnb/lifecycle/detector\": stat /cnb/lifecycle/detector: permission denied": unknown

The logs for the image build is stuck at the detect step as shown below: 
===> PREPARE
Build reason(s): CONFIG
CONFIG:
        resources: {}
        - source: {}
        + source:
        +   git:
        +     revision: 82cb521d636b282340378d80a6307a08e3d4a4c4
        +     url: https://github.com/spring-projects/spring-petclinic
Loading secret for "https://index.docker.io/v1/" from secret "tutorial-registry-credentials" at location "/var/build-secrets/tutorial-registry-credentials"
Cloning "https://github.com/spring-projects/spring-petclinic" @ "82cb521d636b282340378d80a6307a08e3d4a4c4"...
Successfully cloned "https://github.com/spring-projects/spring-petclinic" @ "82cb521d636b282340378d80a6307a08e3d4a4c4" in path "/workspace"
===> DETECT

We are using the docker registry and the katakoda single node cluster machine for this testing the kpack, please help us in fixing the issue.

**Comment by matthewmcnew** [comment]
Which stack are you using in this example? Could you share the relevant stack/store/builder configurations?

**Comment by KasiviswanadhPasam** [comment]
Hi Matthew,

I am following the same configuration which is mentioned in the Tutorial.md : https://github.com/pivotal/kpack/blob/master/docs/tutorial.md. I will post the same below for your reference.

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java
  - image: gcr.io/paketo-buildpacks/nodejs
  
---
apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-builder
  namespace: default
spec:
  serviceAccount: tutorial-service-account
  tag: kasivishwa/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs

**Comment by matthewmcnew** [comment]
Hmm, I was able to verify that seems to be an issue with the katakoda environment. Are you able to test and use kpack on another cluster?

**Comment by KasiviswanadhPasam** [comment]
we have to deploy this in our PKS clusters, so I have tested that with the Katakoda environment. As this is failing in this environment I also tried in our PKS clusters but at that time we are using our Harbor registry for storing the images. The stack, store configuration remains the same. Please find the configurations for builder & secret below:

Secret Configuration:
kubectl create secret docker-registry registry-secret \
    --docker-username=********** \
    --docker-password=********** \
    --docker-server=https://harbor.development.ondemand-wipro.com \
    --namespace default

Builder Confuguration:
piVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-builder
  namespace: default
spec:
  serviceAccount: registry-service-account
  tag: harbor.development.ondemand-wipro.com/builder
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
    - 
we are using the release-0.2.2.yaml for deploying the kpack. If we use this configuration the builder is  not in ready state.

**Comment by matthewmcnew** [comment]
Could you share the status of the builder resource?

**Comment by KasiviswanadhPasam** [comment]
kp builder list
NAME          READY    STACK    IMAGE
my-builder    false

 kp builder status my-builder
Status:    Not Ready
Reason:    Get "https://HARBOR_URL/v2/": x509: certificate signed by unknown authority

We are using the certificates generated from the pivotal.

**Comment by matthewmcnew** [comment]
Hi @KasiviswanadhPasam, It looks like you need to provide the necessary ca cert to kpack. Closing in favor of this issue: https://github.com/pivotal/kpack/issues/207

**Comment by KasiviswanadhPasam** [comment]
Hi @matthewmcnew, I have added the cert as well to the kpack by creating the configMap and added that to the kpack controller as shown below: 
volumes:
       - name: custom-cert
         configMap:
           name: custom-cert
      containers:
      - name: controller
        image: gcr.io/cf-build-service-public/kpack/controller@sha256:101143de3d1abe2d2f738ce96b5991cd085ecc6f0e8dc761b940dd1cd346b864
        volumeMounts:
         - name: custom-cert
           mountPath: /etc/ssl/certs/ca.crt
        env:
        - name: SSL_CERT_DIR
          value: /etc/ssl/certs/ca.crt

And the issue: #207 ,  I didn't get exactly what he has done and no proper documentation for that. He mentioned clone the two images ClusterBuilder and BUILD_INIT_IMAGE and in the release.yaml for the kpack there is no clusterbuilder image and only i can see the build-init-image as shown in the snippet 
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-init-image
  namespace: kpack
data:
  image: gcr.io/cf-build-service-public/kpack/build-init@sha256:ee73f0c697c2c0f71c263cd5254fd02309fe7a07a8141290c63e37c9b401f817

If possible can you please give some clarity about this, so that we can try accordingly. we are having our private harbor repositories and I have got the root cert of it and added to the kpack controller deployment as shown above as configmap but still we are getting the error mentioned below: 
 kp builder status my-builder
Status:    Not Ready
Reason:    HEAD https://HARBOR_URL/v2/builder/blobs/sha256:7a3dbe310959ca5d125c5afcdfb1bf029aef2c1cebb47b9c629613766
b051c8b: unsupported status code 400
