### ISSUE TITLE
invalid credentials to fetch git repository:

### ISSUE THREAD

**Issue by sbalajisivaram** [pivotal/kpack#656]
Hi Community,
Need help, I'm using my own git repo which is mfa enabled to manage my source code when i'm trying to build my container image i'm getting an error  "invalid credentials to fetch git repository: " even though i'm passing PAT that i created from my git.

Steps i've tried:
Since i'm new to buildpacks & kpack i followed this tutorial(https://github.com/pivotal/kpack/blob/master/docs/tutorial.md) to start with so i have installed kpack from the latest release
1. Created a kubernetes secret for my git by following this https://github.com/pivotal/kpack/blob/master/docs/secrets.md
2. Also created a personal access token since my git is MFA enabled (please be informed i can clone the git repo with the PAT i created)
3. created a service account to reference the secret i created for git
4. builder, store & stack resources are created in my cluster as per the kpack doument
5. Image manifest to create a container image

### git secret yaml
apiVersion: v1
kind: Secret
metadata:
  name: k8reg-git
  namespace: default
  annotations:
    kpack.io/git: <my git url>
type: kubernetes.io/basic-auth
stringData:
  username: <my username>
  password: <my PAT>

---
### service account yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-sa
secrets:
  - name: k8reg-acr
  - name: k8reg-git

---
### myimage.yaml
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: kpack-app-image
  namespace: default
spec:
  tag: <my container registry>
  serviceAccount: kpack-sa
  builder:
    name: kpack-builder
    kind: Builder
  cacheSize: "3Gi"
  failedBuildHistoryLimit: 20
  successBuildHistoryLimit: 20
  source:
    git:
      url: <my git url>
      revision: main
---

when i check the logs the error I get
logs:
===> PREPARE
Build reason(s): CONFIG
CONFIG:
        resources: {}
        - source: {}
        + source:
        +   git:
        +     revision: main
        +     url: <my git url>
Loading secrets for "my container registry "k8reg-acr"
Loading secrets for "my git url" from secret "k8reg-git"
Cloning "my git url" @ "main"...
invalid credentials to fetch git repository: my git url

 
Please let me know if more details required.

**Comment by matthewmcnew** [comment]
Hi @sbalajisivaram, It looks like this might be an issue with the how the git secret is annotated. The `kpack.io/git` annotation should only include the host of the git repository. So, if you are on github that should be "https://github.com"

**Comment by sbalajisivaram** [comment]
@matthewmcnew, that worked. thanks.
