### ISSUE TITLE
typo in tutorial

### ISSUE THREAD

**Issue by mingxiao** [pivotal/kpack#664]
This [line](https://github.com/pivotal/kpack/blame/master/docs/tutorial.md#L116) in the tutorial is very confusing: `The builder order will the order in which buildpacks are used in the builder.`

I think the line should read `The builder order will _determine_ the order in which buildpacks are used in the builder.`

**Comment by matthewmcnew** [comment]
Whoops! Thanks for the catch @mingxiao. Could you PR that typo fix in?
