### ISSUE TITLE
Allow the path to a project.toml be configured 

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#705]
https://github.com/pivotal/kpack/pull/690 adds support from project.toml but, will only find a `project.toml` in the root of supplied source with the name `project.toml`. While this behavior matches the default behavior of pack, pack also provides the a pack build `--descriptor` flag which allows users to set the path to a project descriptor. To enable the same behavior in kpack the image and build type should support providing the path to the descriptor in the `spec.build`.

Adding this functionality, naturally makes sense as an api addition to the new api being introduced in the `0.4.0` release.

**Comment by matthewmcnew** [comment]
CC' @genevieve. I heard you might have a unique usecase here?

**Comment by jromero** [comment]
@matthewmcnew is there an RFC (or otherwise high-level view) of changes incorporated in API 0.4.0? Or is it more that it's to signify that "it's ok to break compatibility"?

**Comment by matthewmcnew** [comment]
@jromero We plan on releasing a new api version alongside the existing v1alpha1 in 0.4. So, this new api version is an opportunity to include any/all breaking changes we would like to incorporate into kpack. At this time we have tagged everything `0.4` that we would like to include.

**Comment by samj1912** [comment]
Fixed in https://github.com/pivotal/kpack/pull/800. Can be closed.
