### ISSUE TITLE
Tutorial can't be completed on kind

### ISSUE THREAD

**Issue by astefanova** [pivotal/kpack#727]
Hi, 👋 ,

I am running `kind 0.11.1` and kpack `release-0.2.2.yaml`. When I try to create the builder CR, I get the following error:

```
validating buildpack paketo-buildpacks/bellsoft-liberica@8.1.2: unsupported buildpack api: 0.6, expecting: 0.2, 0.3, 0.4, 0.5
```

Any ideas how I could go around it?

Thanks and have a nice day. :)

**Comment by tomkennedy513** [comment]
Kpack 0.2.x doesn't support platform api 0.6 because of the lifecycle it is shipped with. You can update the lifecycle in kpack by editing the lifecycle-image config map in the kpack namespace, but the easiest thing to do would be to use kpack 0.3.0

**Comment by astefanova** [comment]
Thanks a lot. It seems I started it more than 4 days ago, when the lates version was 2.2.0. It works now, I am closing the issue. :)
