### ISSUE TITLE
Support buildpacks with the wildcard stack

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#741]
Currently, buildpacks with a wildcard stack will not be properly recognized by kpack. 

RFC: https://github.com/buildpacks/rfcs/pull/97

**Comment by mgibson1121** [comment]
Is there any way to validate this?  Correct me if I'm wrong but seems like it could be validated by the UBI stories when they are finished.

**Comment by matthewmcnew** [comment]
This can be validated with any of the heroku jvm buildpacks: https://github.com/heroku/buildpacks-jvm/releases.

**Comment by matthewmcnew** [comment]
You can also package a simple buildpack locally with the wildcard stack with `pack buildpack new` & edit buildpack.toml & `pack buildpack package`
