### ISSUE TITLE
Rewording needed?

### ISSUE THREAD

**Issue by BRONSOLO** [pivotal/kpack#792]
Super small issue - I believe the description of the runImage parameter needs to be reworded here: https://github.com/pivotal/kpack/blob/4e5647354c3a55fee655199646059efd93f9b0c4/cmd/build-init/main.go#L30.

**Comment by matthewmcnew** [comment]
Good catch! @BRONSOLO could you make a real simple PR for that?

**Comment by BRONSOLO** [comment]
Sure thing @matthewmcnew! I just proposed a change.
