### ISSUE TITLE
Allow manual control on the build generation from image reconciler

### ISSUE THREAD

**Issue by ArieShout** [pivotal/kpack#81]
Currently, the image automatically creates new build whenever some factors changes (source, upstream git with `SourceResolver`, builder, etc.). Plus the build name will be automatically generated. This makes the build behavior hard to predict:

* When I update the source config, will I get a new build?
   * Yes - if there isn't a running build and the source config is different than current.
   * No - if there is a running build, only the last update will trigger a build after the previous build completes.
* If I update the image label, will I get a new build?
   * Yes - if the git revision referenced by tag name / branch name changed
   * No - if no changes in the git revision
* If I update the access token in the blob URL, will I get a new build?
   * Yes - but it should not because the actual blob storage is not changed.

It may worth add a special field (maybe `manualBuildId`) to control the build behavior:
   * Prevent build if specified with some special value, `0` for example
   * Go with current build behavior if not specified
   * If specified with other value, generated build only when this value changes and there is not corresponding build regardless of the source change. The build name should be constructed from the specified value.

      In this way, when I change this value, I can query the build to this change directly.

**Comment by matthewmcnew** [comment]
For granular control we recommend using [builds](https://github.com/pivotal/kpack/blob/master/docs/build.md) directly. I am going to close this for now.
