### ISSUE TITLE
Change kp CLI commands to have image-resource as primary alias, and remove references

### ISSUE THREAD

**Issue by sampeinado** [pivotal/kpack#819]
Replace all references in kp CLI commands, command output, and help output to refer to “image resource” instead of “image” or “image configuration” 

Example: 
![CURRENT CLI](https://user-images.githubusercontent.com/35495560/132034503-4822e2cd-f4bd-4738-bfe8-b9eeb1ba8997.png)
![PROPOSED CLI](https://user-images.githubusercontent.com/35495560/132034505-e4b72c05-ee4b-45d5-8f29-d26ba2ffdff1.png)

**Comment by matthewmcnew** [comment]
Could we move this issue to the kpack-cli repo?

**Comment by sampeinado** [comment]
done

**Comment by matthewmcnew** [comment]
Closing in favor of: https://github.com/vmware-tanzu/kpack-cli/issues/207
