### ISSUE TITLE
ETA for new release

### ISSUE THREAD

**Issue by tarzzz** [pivotal/kpack#829]
Hi, 

Is there an ETA for new kpack release? I am specifically looking for as to when https://github.com/pivotal/kpack/pull/670 will be available in a release.

If someone can point me to the instructions to build kpack from `master` branch that will be helpful as well.

**Comment by matthewmcnew** [comment]
Hi @tarzzz, The next kpack release is scheduled in the next couple of weeks. 

We have basic docs on building kpack from the `main` branch [here](https://github.com/pivotal/kpack/blob/main/docs/local.md).
