### ISSUE TITLE
Enable triggering builds without config/buildpack change

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#84]

**Comment by donovanmuller** [comment]
Would this issue also cater for disabling the `SourceResolver` polling of a source and triggering builds? I.e. If I wanted to integrate kpack into existing pipelines, I would need to be able to disable the source polling and have manual control when builds are triggered.

**Comment by scothis** [comment]
@donovanmuller You can always create a `Build` resource directly to create a one-off or on-demand builds

**Comment by matthewmcnew** [comment]
Closing this as we support "triggering" builds by adding a build needed annotation to the last build. This is available with the kpack cli.
