### ISSUE TITLE
Support Platform api 0.7 / platform api 0.8

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#886]
**Why**
To support the full feature set of the Lifecycle `v0.13.x` including sBOM support, kpack builds need to support platform api 0.8. 

**What**
Kpack builds should support and elect to use [platform api 0.8](https://github.com/buildpacks/spec/releases) if available on the executed lifecycle. If the 0.8 platform api is not available the build should utilize the 0.7 platform api. The included version of the lifecycle in the kpack release should be updated to the most recent release of the lifecycle. 

**Complications**
* This will be a slightly more complicated update because the analyze phase moves before the detect phase.

**Comment by samj1912** [comment]
I am happy to help out with this.

**Comment by samj1912** [comment]
The PR should be done for implementing support for both 0.7 and 0.8
