### ISSUE TITLE
I am getting ERROR while executing the command "kp build logs tutorial-image -n default"

### ISSUE THREAD

**Issue by gaiwey** [pivotal/kpack#927]
![image](https://user-images.githubusercontent.com/21032881/155692916-9647edc9-5f86-4402-9ae3-c080262c6eb8.png)

The operation steps are performed according to the README

Guys, help me see where is the problem? How to solve it?

**Comment by matthewmcnew** [comment]
Hi @gaiwey, This is likely that the fsgroup permissions are not being set properly by the default storage class on the cluster. What version of kubernetes and where is this running?

**Comment by matthewmcnew** [comment]
Closing for now. Please reopen if you are still having issues!
