### ISSUE TITLE
`kubectl get img` does not return any kpack images

### ISSUE THREAD

**Issue by ciberkleid** [pivotal/kpack#929]
Calling `kubectl api-resources` shows that a kpack Image resource should have four aliases:
```
$ k api-resources | grep kpack | grep -i image
images                            cnbimage,cnbimages,img,imgs   kpack.io/v1alpha2                           true         Image
```

Three of these aliases work:
```
$ k get cnbimage
NAME     LATESTIMAGE                                                                                                      READY
manual   gcr.io/fe-ciberkleid/demo/app@sha256:c3a9f2e8f8eced4f6779aa99419642c164665768872960c9c7737bd1146cd044   True

$ k get cnbimages
NAME     LATESTIMAGE                                                                                                      READY
manual   gcr.io/fe-ciberkleid/demo/app@sha256:c3a9f2e8f8eced4f6779aa99419642c164665768872960c9c7737bd1146cd044   True

$ k get imgs
NAME     LATESTIMAGE                                                                                                      READY
manual   gcr.io/fe-ciberkleid/demo/app@sha256:c3a9f2e8f8eced4f6779aa99419642c164665768872960c9c7737bd1146cd044   True
```

However, one of the aliases (`img`) does not work:
```
$ k get img
No resources found in default namespace.
```

**Comment by matthewmcnew** [comment]
Hi @ciberkleid, Sometimes there is conflict on the img alias ([Do you have knative serving installed by chance?](https://github.com/knative/serving/blob/6c3394bb4d5a365ba84d147a42dfbbd520872f66/vendor/knative.dev/caching/config/image.yaml)). 

You should always be able to get kpack images with with `kubectl get img.kpack.io`.

**Comment by ciberkleid** [comment]
Yes, I had knative-serving installed as well. Does that mean there's no way
to solve this if both are installed?

**Comment by matthewmcnew** [comment]
Ultimately, this is a kubectl issue. Could you open an issue on kubernetes to change which resource takes precedence on name conflict? 

Related, it looks like there was as issue to warn on the name conflict: https://github.com/kubernetes/kubernetes/issues/94860.
