### ISSUE TITLE
kpack controller and builder comaptability issue

### ISSUE THREAD

**Issue by venkat36732395** [pivotal/kpack#950]
Hi Team,

After i installing the new kpack version into kubernetes cluster , I am facing the below issue. Actually I have followed the below process and need help on how we can resolve the issue with builder and kpack-controller?

**Kpack manual steps:**

1. Install Certificate Injection Webhook
2. Install Kpack
3. Configure Kpack

**panic: runtime error**: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x55dde2d04f9d]
[clusterstack yaml files.txt](https://github.com/pivotal/kpack/files/8459250/clusterstack.yaml.files.txt)

Thanks,
venkat.

**Comment by matthewmcnew** [comment]
Could you provide the full logs from the `kpack-controller`?

**Comment by matthewmcnew** [comment]
This is fixed in: https://github.com/pivotal/kpack/pull/946

**Comment by venkat36732395** [comment]
Hi matthew, it works for kpack tool in kubernetes cluster?

**Comment by matthewmcnew** [comment]
Yes, it is now published in this release:  https://github.com/pivotal/kpack/releases/tag/v0.5.3
