### ISSUE TITLE
Build from Zip Blob with Unknown Parent Folder Name

### ISSUE THREAD

**Issue by diarmuidie** [pivotal/kpack#957]
We're using the build resource directly to build from a zipped source:
```
source:
  blob:
    url: "https://example.com/source.zip"
  subPath: ""
```

When unzipped that `source.zip` file has a parent directory and within that is the source of the application. Because the zip is coming from a third party (Github, or direct from the our end users in our case) the name of the parent folder is not consistent enough that we can use the `subPath` to set it.

For example if you download the source of a Github repo using the [Github zipball api endpoint](https://docs.github.com/en/rest/repos/contents#download-a-repository-archive-zip) you get a different parent folder name depending on if it's a public (`{org_name}-{repo_name}-{short_sha}`) or private (`{org_name}-{repo_name}-{long_sha}`) repo.

One way to work around this if there was an option to set something like the tar `--strip-components` so we could tell the [archive package](https://github.com/pivotal/kpack/blob/main/pkg/archive/archive.go) to ignore the first N paths when extracting (this is what [Paketos Libpak extraction package does](https://github.com/paketo-buildpacks/libpak/blob/8979ae3422306d7bf5a10c136bd187807b4e744d/crush/crush.go#L240))

Do you have any other thoughts or ideas on how to solve this?

Thanks!

**Comment by matthewmcnew** [comment]
That is an interesting problem! Providing `strip-components` would be an interesting addition to the `source.blob` kpack api. In the meantime would programmatically calculating the subpath from the blob url be possible? Perhaps from an earlier automation job?

**Comment by diarmuidie** [comment]
Hey @matthewmcnew, ya for now we're looking at having a component re-format the zip into a standard format before it gets to kpack, but it would be nice not to have to do that! Thanks
