### ISSUE TITLE
image building does not stop

### ISSUE THREAD

**Issue by wind57** [pivotal/kpack#979]
This is my first issue, so please be gentle with me :)

First of all here is [reproducible example](https://github.com/wind57/kpack). You can totally ignore the comments, since I mainly made them for myself.

The problem is that the build never stops, I mean there are always new "builds", even if nothing changes in `main` branch in `https://github.com/ciberkleid/hello-java.git` from `image.yaml`.

If you try this sample, you would see that your git repo is filled with images, it just never "stops".

If I use `0.5.3` instead of `0.5.4` - it works exactly as I would expect it to : single image in dockerhub.

If this needs more details - do not hesitate to ask, will be more then happy to provide them. thank you

**Comment by jjbustamante** [comment]
Hi @wind57, is this issue similar to: #641?

**Comment by wind57** [comment]
Yup! Closing since that is already tracked. Thank you

**Comment by jjbustamante** [comment]
Thanks a lot for the reproduction steps, I will be working on fixing the issue and that is great insight!
