### ISSUE TITLE
"docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." error message occur in kpack-controller pod after upgrading kpack version to 0.6.0

### ISSUE THREAD

**Issue by zhoufenqin** [pivotal/kpack#980]
After upgrading to kpack 0.6.0, error logs with `time="2022-06-21T12:01:24Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=serviceacr.azurecr.io` occur multiple times in kpack-controller pod

With the same buildpacks version, these errors are not occur in kpack 0.5.2

The error won't block create resources like builder, but too many error logs.  Is it a bug?

![image](https://user-images.githubusercontent.com/8765864/174796143-33011866-4cb9-4a22-9ec2-419a96e6813d.png)

**Comment by bjethwan** [comment]
I'm facing the same issue. 
I was trying to use the tutorial for the first time on local KIND cluster.
In my case the clusterstack was never coming to ready state
```
    Message:               Get "https://auth.docker.io/token?scope=repository%3Apaketobuildpacks%2Fbuild%3Apull&service=registry.docker.io": dial tcp: i/o timeout
    Status:                False
```
```
{"level":"info","ts":"2022-06-21T16:56:00.5705221Z","logger":"controller","caller":"controller/controller.go:548","msg":"Reconcile succeeded","commit":"0a30a5a","knative.dev/kind":"clusterstores.kpack.io","knative.dev/traceid":"722a20bb-dcbc-4c14-aa4e-d714c54ffb28","knative.dev/key":"default","duration":3.7938415}
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
time="2022-06-21T16:56:00Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=gcr.io
{"level":"info","ts":"2022-06-21T16:56:03.2579495Z","logger":"controller","caller":"controller/controller.go:548","msg":"Reconcile succeeded","commit":"0a30a5a","knative.dev/kind":"clusterstores.kpack.io","knative.dev/traceid":"43b16baf-adc0-4962-9921-871cc91dc95d","knative.dev/key":"default","duration":2.5999424}
time="2022-06-21T16:56:31Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=index.docker.io
{"level":"error","ts":"2022-06-21T16:57:01.3489083Z","logger":"controller","caller":"controller/controller.go:564","msg":"Reconcile error","commit":"0a30a5a","knative.dev/kind":"clusterstacks.kpack.io","duration":30.2053526,"error":"Get \"https://auth.docker.io/token?scope=repository%3Apaketobuildpacks%2Fbuild%3Apull&service=registry.docker.io\": dial tcp: i/o timeout","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:477"}
time="2022-06-21T16:57:01Z" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." serverURL=index.docker.io
{"level":"error","ts":"2022-06-21T16:57:31.5977066Z","logger":"controller","caller":"controller/controller.go:564","msg":"Reconcile error","commit":"0a30a5a","knative.dev/kind":"clusterstacks.kpack.io","duration":30.2659186,"error":"Get \"https://auth.docker.io/token?scope=repository%3Apaketobuildpacks%2Fbuild%3Apull&service=registry.docker.io\": dial tcp: i/o timeout","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:477"}
{"level":"error","ts":"2022-06-21T16:58:21.2148753Z","logger":"controller","caller":"controller/controller.go:564","msg":"Reconcile error","commit":"0a30a5a","knative.dev/kind":"builders.kpack.io","duration":0.1029777,"error":"stack base is not ready","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:477"}
{"level":"error","ts":"2022-06-21T16:58:21.2155021Z","logger":"controller","caller":"controller/controller.go:564","msg":"Reconcile error","commit":"0a30a5a","knative.dev/kind":"builders.kpack.io","duration":0.0002362,"error":"stack base is not ready","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220121092305-3ba5d72e310a/controller/controller.go:477"}
```

**Comment by bjethwan** [comment]
I got the below error when I moved from using 0.6.0 release to 0.5.4 release...

`{"severity":"ERROR","timestamp":"2022-06-21T17:38:52.8808955Z","logger":"controller","caller":"controller/controller.go:564","message":"Reconcile error","commit":"3ba848e","duration":"30.1311478s","error":"Get \"https://auth.docker.io/token?scope=repository%3Apaketobuildpacks%2Fbuild%3Apull&service=registry.docker.io\": dial tcp: i/o timeout","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210902173607-844a6bc45596/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210902173607-844a6bc45596/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210902173607-844a6bc45596/controller/controller.go:477"}`

**Comment by tylerphelan** [comment]
@bjethwan in the logs the `clusterstore` did successfully reconcile which suggests the `dial tcp: i/o timeout` is not related to the cred helper message and instead is network-related.

**Comment by zhoufenqin** [comment]
@tylerphelan  @matthewmcnew I saw [this PR](https://github.com/pivotal/kpack/commit/f98f1ffdb1c81b32d51b4087a470fb52ec1ca090#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R89) includes `amazon-ecr-credential-helper` and this error log print from [awslabs/amazon-ecr-credential-helper/blob/main/ecr-login/api/client.go](https://github.com/awslabs/amazon-ecr-credential-helper/blob/main/ecr-login/api/client.go#L73), It's not reasonable to print the error msg when we don't use the amazon ecr. Can you help to check it again and fix this?

**Comment by matthewmcnew** [comment]
@zhoufenqin This error message is due to the underlying ECR cred helper printing unnecessary logging statements and should not affect the usage of ECR or other registries. Is the concern primarily because it is adding noise to the logs?

**Comment by zhoufenqin** [comment]
> @zhoufenqin This error message is due to the underlying ECR cred helper printing unnecessary logging statements and should not affect the usage of ECR or other registries. Is the concern primarily because it is adding noise to the logs?

yes, @matthewmcnew, there are too many noise logs, and I found the speed of creating resources such as builder/cnbimage is a bit slower(Maybe not related to this).
Besides, we will return build logs to customers, these kinds of logs will also appear in build pod logs, it's a little confusing to customers.

e.g
![image](https://user-images.githubusercontent.com/8765864/176578496-4990732c-719c-4bf4-8679-41d713d49e01.png)

**Comment by matthewmcnew** [comment]
@zhoufenqin That makes sense. The error in logs output is pretty severe. This is high priority to fix in a kpack 0.6.x patch.

**Comment by tylerphelan** [comment]
re-opening as this will be fixed on the next release of kpack

**Comment by tylerphelan** [comment]
fixed in https://github.com/pivotal/kpack/releases/tag/v0.6.1
