### ISSUE TITLE
Unable to get rid of this error: Get "https://auth.docker.io/token?scope=repository%3Apaketobuildpacks%2Fbuild%3Apull&service=registry.docker.io": dial tcp: i/o timeout

### ISSUE THREAD

**Issue by bjethwan** [pivotal/kpack#981]
Unable to get rid of this error: Get "https://auth.docker.io/token?scope=repository%3Apaketobuildpacks%2Fbuild%3Apull&service=registry.docker.io": dial tcp: i/o timeout, while creating clusterstack as per the tutorial.

```
I was using KIND
kindest/node:v1.23.1
```

**Comment by matthewmcnew** [comment]
Could you show the context of this error? What command/resource did you see on this error?

**Comment by matthewmcnew** [comment]
Closing. Please reopen if you still have this issue.
