### ISSUE TITLE
Support istio sidecar injection in build namespaces

### ISSUE THREAD

**Issue by tylerphelan** [pivotal/kpack#986]
Istio/envoy proxy does not work well with kpack, especially in build namespaces, because kpack uses init containers for the CNB process.

Can we improve this to support istio networking on kpack clusters?

**Comment by tomkennedy513** [comment]
Some context: https://istio.io/latest/docs/setup/additional-setup/cni/#compatibility-with-application-init-containers

**Comment by matthewmcnew** [comment]
This may require a significant change to how kpack executes builds. It would be helpful to have an RFC especially if it introduces a change to the user experience.

**Comment by tomkennedy513** [comment]
draft pr: #999
