### ISSUE TITLE
Create build cache pvc with specified storageClassName

### ISSUE THREAD

**Issue by zhoufenqin** [pivotal/kpack#994]
# Problem
Build pod may be blocked when the pod is scheduled in different zones

When enabling **"Zone Redundant"** in our service, the build pod may be scheduled in different zones,  it will not able to be scheduled finally because it cannot connect to the volume from another zone. 
Just like this issue: https://stackoverflow.com/questions/51946393/kubernetes-pod-warning-1-nodes-had-volume-node-affinity-conflict

The build pod will always in `Pending` status because it can't find an enable node to deploy
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/8765864/179755374-3f5068f1-8238-4d1f-ad8f-ef3a2673e33a.png)

When we set `Spec.cache.volume.size` in Image resource, it will create a PVC first, and the storageClassName in PVC is "default". Is it possible to specify a storageClassName for the PVC so we can customized the StorageClass for PV? Or is there any better way to solve this kind of issued caused by "Zone Redundant"?

**Comment by tylerphelan** [comment]
Thank you for this issue and ideas! We have thought about this and want to add this behavior: https://github.com/pivotal/kpack/issues/994

We should use this issue to track. Closing the other.

**Comment by matthewmcnew** [comment]
@zhoufenqin it seems like the best solution is to provide a mechanism to specify an alternative storage class as originally suggested on https://github.com/pivotal/kpack/issues/514. In the meantime, would it be possible to change what the default storage class is on your cluster to use a different storage class?

**Comment by zhoufenqin** [comment]
@matthewmcnew, as we discuss in [pivotaltracker](https://www.pivotaltracker.com/story/show/182833089), it's not easy for us to update the default storage class because other features may use the `default` storage class, and not only my cluster, I'll provide this cache feature for customers' clusters. Currently, we disable the cache feature, so I hope to know which kpack version will release this feature? thanks :)

**Comment by zhoufenqin** [comment]
@matthewmcnew  @tylerphelan can I know which kpack version will release this feature?

**Comment by matthewmcnew** [comment]
@zhoufenqin We are targeting this for the 0.7.0 release which will be released in the next couple of week but, it may be pushed to the 0.8.0 release which would be a fast follow release to the 0.7.0.

**Comment by tylerphelan** [comment]
how should modifying the image resource's storage class name work?
The risk I see is differentiating between these two scenarios:
- There is an existing image with the storage class name unset, therefore the PVC uses the default storage class name
- A user has modified the current image resource storage class name to unset - how can we know if the storageclass on the PVC has changed or not?

**Comment by matthewmcnew** [comment]
How does the PVC behave when its storage class is updated?

**Comment by tylerphelan** [comment]
@matthewmcnew the field is immutable for pvc's so it fails to update via a validation failure

**Comment by matthewmcnew** [comment]
Shouldn't the kpack image do the same to prevent modification of the storage class?

**Comment by tylerphelan** [comment]
>Shouldn't the kpack image do the same to prevent modification of the storage class?

I think it's a good idea.
