### ISSUE TITLE
Utilize Platform API 0.9 when available

### ISSUE THREAD

**Issue by matthewmcnew** [pivotal/kpack#998]
### Background 
When builds are executed with [Platform API 0.9 or greater they will omit the legacy BOM from the output image](https://github.com/buildpacks/lifecycle/issues/808). This will prevent the image from having potentially problematic large label sizes. This should resolve [some issues](https://github.com/pivotal/kpack/issues/893) with reported images built by kpack.

### Additional Context
* This should be documented as a possible breaking change.
* This should be released alongside the bom support being removed from kp. https://github.com/vmware-tanzu/kpack-cli/pull/261

**Comment by matthewmcnew** [comment]
For some consumers of kpack built images, the removal of the "legacy" bom will be a breaking change. To mitigate this the kpack should provide a mechanism to configure which platform api is used. It may make sense to do this at a cluster level.

**Comment by tylerphelan** [comment]
Notes:
- Make kpack controller configurable with a `MAXIMUM_PLATFORM_API_VERSION` configuration

**Comment by tylerphelan** [comment]
Includes https://github.com/pivotal/kpack/issues/1009

**Comment by tomkennedy513** [comment]
created #1024 to handle configurable platform api version
